// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionInvVoucher
{
    public int AccessionInvVoucherId { get; set; }

    public int InventoryId { get; set; }

    public int? CollectorCooperatorId { get; set; }

    public string CollectorVoucherNumber { get; set; }

    public string VoucherLocation { get; set; }

    public DateTime? VoucheredDate { get; set; }

    public string VoucheredDateCode { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string HerbariumBarcode { get; set; }

    public virtual Cooperator CollectorCooperator { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}