// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionPedigree
{
    public int AccessionPedigreeId { get; set; }

    public int AccessionId { get; set; }

    public DateTime? ReleasedDate { get; set; }

    public string ReleasedDateCode { get; set; }

    public int? MaleAccessionId { get; set; }

    public string MaleExternalAccession { get; set; }

    public int? FemaleAccessionId { get; set; }

    public string FemaleExternalAccession { get; set; }

    public string CrossCode { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Accession Accession { get; set; }

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Accession FemaleAccession { get; set; }

    public virtual Accession MaleAccession { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}