// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionSource
{
    public int AccessionSourceId { get; set; }

    public int AccessionId { get; set; }

    public int? GeographyId { get; set; }

    public string AcquisitionSourceCode { get; set; }

    public string SourceTypeCode { get; set; }

    public DateTime? SourceDate { get; set; }

    public string SourceDateCode { get; set; }

    public string IsOrigin { get; set; }

    public decimal? QuantityCollected { get; set; }

    public string UnitQuantityCollectedCode { get; set; }

    public string CollectedFormCode { get; set; }

    public int? NumberPlantsSampled { get; set; }

    public int? ElevationMeters { get; set; }

    public string CollectorVerbatimLocality { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public int? Uncertainty { get; set; }

    public string FormattedLocality { get; set; }

    public string GeoreferenceDatum { get; set; }

    public string GeoreferenceProtocolCode { get; set; }

    public string GeoreferenceAnnotation { get; set; }

    public string EnvironmentDescription { get; set; }

    public string AssociatedSpecies { get; set; }

    public string IsWebVisible { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Accession Accession { get; set; }

    public virtual ICollection<AccessionSourceMap> AccessionSourceMaps { get; set; } = new List<AccessionSourceMap>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Geography Geography { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SourceDescObservation> SourceDescObservations { get; set; } = new List<SourceDescObservation>();
}