// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionQuarantine
{
    public int AccessionQuarantineId { get; set; }

    public int AccessionId { get; set; }

    public string QuarantineTypeCode { get; set; }

    public string ProgressStatusCode { get; set; }

    public int CustodialCooperatorId { get; set; }

    public DateTime? EnteredDate { get; set; }

    public DateTime? EstablishedDate { get; set; }

    public DateTime? ExpectedReleaseDate { get; set; }

    public DateTime? ReleasedDate { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Accession Accession { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator CustodialCooperator { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}