// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionInvGroup
{
    public int AccessionInvGroupId { get; set; }

    public string GroupName { get; set; }

    public int? MethodId { get; set; }

    public string IsWebVisible { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual ICollection<AccessionInvGroupAttach> AccessionInvGroupAttaches { get; set; } = new List<AccessionInvGroupAttach>();

    public virtual ICollection<AccessionInvGroupMap> AccessionInvGroupMaps { get; set; } = new List<AccessionInvGroupMap>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Method Method { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}