// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Accession
{
    public int AccessionId { get; set; }

    public string Doi { get; set; }

    public string AccessionNumberPart1 { get; set; }

    public int? AccessionNumberPart2 { get; set; }

    public string AccessionNumberPart3 { get; set; }

    public string IsCore { get; set; }

    public string IsBackedUp { get; set; }

    public int? BackupLocation1SiteId { get; set; }

    public int? BackupLocation2SiteId { get; set; }

    public string StatusCode { get; set; }

    public string LifeFormCode { get; set; }

    public string ImprovementStatusCode { get; set; }

    public string ReproductiveUniformityCode { get; set; }

    public string InitialReceivedFormCode { get; set; }

    public DateTime? InitialReceivedDate { get; set; }

    public string InitialReceivedDateCode { get; set; }

    public int TaxonomySpeciesId { get; set; }

    public string IsWebVisible { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string LifeCycleCode { get; set; }

    public string LifeHabitCode { get; set; }

    public string LifeSexCode { get; set; }

    public virtual ICollection<AccessionAction> AccessionActions { get; set; } = new List<AccessionAction>();

    public virtual ICollection<AccessionIpr> AccessionIprs { get; set; } = new List<AccessionIpr>();

    public virtual AccessionPedigree AccessionPedigreeAccession { get; set; }

    public virtual ICollection<AccessionPedigree> AccessionPedigreeFemaleAccessions { get; set; } = new List<AccessionPedigree>();

    public virtual ICollection<AccessionPedigree> AccessionPedigreeMaleAccessions { get; set; } = new List<AccessionPedigree>();

    public virtual ICollection<AccessionQuarantine> AccessionQuarantines { get; set; } = new List<AccessionQuarantine>();

    public virtual ICollection<AccessionSource> AccessionSources { get; set; } = new List<AccessionSource>();

    public virtual Site BackupLocation1Site { get; set; }

    public virtual Site BackupLocation2Site { get; set; }

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<WebOrderRequestItem> WebOrderRequestItems { get; set; } = new List<WebOrderRequestItem>();

    public virtual ICollection<WebUserCartItem> WebUserCartItems { get; set; } = new List<WebUserCartItem>();
}