// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionInvAttachValidation
{
    public int AccessionInvAttachValidationId { get; set; }

    public int AccessionInvAttachId { get; set; }

    public string IsVirtualPathValid { get; set; }

    public string IsThumbnailVirtualPathValid { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }
}