// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionInvName
{
    public int AccessionInvNameId { get; set; }

    public int InventoryId { get; set; }

    public string CategoryCode { get; set; }

    public string PlantName { get; set; }

    public int? PlantNameRank { get; set; }

    public int? NameGroupId { get; set; }

    public int? NameSourceCooperatorId { get; set; }

    public string IsWebVisible { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual NameGroup NameGroup { get; set; }

    public virtual Cooperator NameSourceCooperator { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}