// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionInventoryAttachLookup
{
    public int AccessionId { get; set; }

    public int AccessionInvAttachId { get; set; }

    public string IsWebVisible { get; set; }

    public string VirtualPath { get; set; }

    public string ThumbnailVirtualPath { get; set; }

    public string CategoryCode { get; set; }

    public string CopyrightInformation { get; set; }

    public string ContentType { get; set; }
}