// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionLookupAvailability
{
    public int TargetId { get; set; }

    public string Lookup { get; set; }

    public string AvailabilityStatus { get; set; }
}