// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionInvAnnotation
{
    public int AccessionInvAnnotationId { get; set; }

    public string AnnotationTypeCode { get; set; }

    public DateTime AnnotationDate { get; set; }

    public string AnnotationDateCode { get; set; }

    public int? AnnotationCooperatorId { get; set; }

    public int InventoryId { get; set; }

    public int? OrderRequestId { get; set; }

    public int? OldTaxonomySpeciesId { get; set; }

    public int? NewTaxonomySpeciesId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator AnnotationCooperator { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual TaxonomySpecy NewTaxonomySpecies { get; set; }

    public virtual TaxonomySpecy OldTaxonomySpecies { get; set; }

    public virtual OrderRequest OrderRequest { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}