// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AccessionIprOverview
{
    public int AccessionIprId { get; set; }

    public int AccessionId { get; set; }

    public string Lookup { get; set; }

    public string TypeCode { get; set; }

    public string IprNumber { get; set; }

    public string IprCropName { get; set; }

    public string IprFullName { get; set; }

    public DateTime? IssuedDate { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public string ExpirationStatus { get; set; }

    public int? CooperatorId { get; set; }

    public string ApplicationStatus { get; set; }

    public string ApplicationStatusDescription { get; set; }

    public string Note { get; set; }

    public DateTime? AcceptedDate { get; set; }

    public DateTime? ExpectedDate { get; set; }
}