// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AppResource
{
    public int AppResourceId { get; set; }

    public int SysLangId { get; set; }

    public string AppName { get; set; }

    public string FormName { get; set; }

    public string AppResourceName { get; set; }

    public string Description { get; set; }

    public string DisplayMember { get; set; }

    public string ValueMember { get; set; }

    public int? SortOrder { get; set; }

    public string Properties { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual SysLang SysLang { get; set; }
}