// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AppUserItemFolder
{
    public int AppUserItemFolderId { get; set; }

    public string FolderName { get; set; }

    public string FolderType { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public bool? IsShared { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string Category { get; set; }

    public string DataType { get; set; }

    public string Properties { get; set; }

    public string IsFavorite { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }
}