// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class AppUserItemList
{
    public int AppUserItemListId { get; set; }

    public int CooperatorId { get; set; }

    public string TabName { get; set; }

    public string ListName { get; set; }

    public int? IdNumber { get; set; }

    public string IdType { get; set; }

    public int? SortOrder { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Properties { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator Cooperator { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}