// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Citation
{
    public int CitationId { get; set; }

    public int? LiteratureId { get; set; }

    public string CitationTitle { get; set; }

    public string AuthorName { get; set; }

    public int? CitationYear { get; set; }

    public string Reference { get; set; }

    public string DoiReference { get; set; }

    public string Url { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? AccessionId { get; set; }

    public int? MethodId { get; set; }

    public int? TaxonomySpeciesId { get; set; }

    public int? TaxonomyGenusId { get; set; }

    public int? TaxonomyFamilyId { get; set; }

    public int? AccessionIprId { get; set; }

    public int? AccessionPedigreeId { get; set; }

    public int? GeneticMarkerId { get; set; }

    public string TypeCode { get; set; }

    public int? UniqueKey { get; set; }

    public string IsAcceptedName { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Accession Accession { get; set; }

    public virtual AccessionIpr AccessionIpr { get; set; }

    public virtual AccessionPedigree AccessionPedigree { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual GeneticMarker GeneticMarker { get; set; }

    public virtual Literature Literature { get; set; }

    public virtual Method Method { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}