// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CodeValueLookup
{
    public int CodeValueId { get; set; }

    public int CodeValueLangId { get; set; }

    public string GroupName { get; set; }

    public string Value { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }
}