// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CooperatorGroup
{
    public int CooperatorGroupId { get; set; }

    public string Name { get; set; }

    public string IsGroupActive { get; set; }

    public int? SiteId { get; set; }

    public string CategoryCode { get; set; }

    public string GroupTag { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual ICollection<CooperatorMap> CooperatorMaps { get; set; } = new List<CooperatorMap>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual Site Site { get; set; }
}