// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Cooperator
{
    public int CooperatorId { get; set; }

    public int? CurrentCooperatorId { get; set; }

    public int? SiteId { get; set; }

    public string LastName { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string Job { get; set; }

    public string Organization { get; set; }

    public string OrganizationAbbrev { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string City { get; set; }

    public string PostalIndex { get; set; }

    public int? GeographyId { get; set; }

    public string SecondaryOrganization { get; set; }

    public string SecondaryOrganizationAbbrev { get; set; }

    public string SecondaryAddressLine1 { get; set; }

    public string SecondaryAddressLine2 { get; set; }

    public string SecondaryAddressLine3 { get; set; }

    public string SecondaryCity { get; set; }

    public string SecondaryPostalIndex { get; set; }

    public int? SecondaryGeographyId { get; set; }

    public string PrimaryPhone { get; set; }

    public string SecondaryPhone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string SecondaryEmail { get; set; }

    public string StatusCode { get; set; }

    public string CategoryCode { get; set; }

    public string OrganizationRegionCode { get; set; }

    public string DisciplineCode { get; set; }

    public string Note { get; set; }

    public int SysLangId { get; set; }

    public int? WebCooperatorId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string VettedStatus { get; set; }

    public string VettedStatusCode { get; set; }

    public string CooperatorIdString { get; set; }

    public virtual ICollection<AccessionAction> AccessionActionCooperators { get; set; } = new List<AccessionAction>();

    public virtual ICollection<AccessionAction> AccessionActionCreatedByNavigations { get; set; } = new List<AccessionAction>();

    public virtual ICollection<AccessionAction> AccessionActionModifiedByNavigations { get; set; } = new List<AccessionAction>();

    public virtual ICollection<AccessionAction> AccessionActionOwnedByNavigations { get; set; } = new List<AccessionAction>();

    public virtual ICollection<Accession> AccessionCreatedByNavigations { get; set; } = new List<Accession>();

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotationAnnotationCooperators { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotationCreatedByNavigations { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotationModifiedByNavigations { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotationOwnedByNavigations { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<AccessionInvAttach> AccessionInvAttachAttachCooperators { get; set; } = new List<AccessionInvAttach>();

    public virtual ICollection<AccessionInvAttach> AccessionInvAttachCreatedByNavigations { get; set; } = new List<AccessionInvAttach>();

    public virtual ICollection<AccessionInvAttach> AccessionInvAttachModifiedByNavigations { get; set; } = new List<AccessionInvAttach>();

    public virtual ICollection<AccessionInvAttach> AccessionInvAttachOwnedByNavigations { get; set; } = new List<AccessionInvAttach>();

    public virtual ICollection<AccessionInvGroupAttach> AccessionInvGroupAttachAttachCooperators { get; set; } = new List<AccessionInvGroupAttach>();

    public virtual ICollection<AccessionInvGroupAttach> AccessionInvGroupAttachCreatedByNavigations { get; set; } = new List<AccessionInvGroupAttach>();

    public virtual ICollection<AccessionInvGroupAttach> AccessionInvGroupAttachModifiedByNavigations { get; set; } = new List<AccessionInvGroupAttach>();

    public virtual ICollection<AccessionInvGroupAttach> AccessionInvGroupAttachOwnedByNavigations { get; set; } = new List<AccessionInvGroupAttach>();

    public virtual ICollection<AccessionInvGroup> AccessionInvGroupCreatedByNavigations { get; set; } = new List<AccessionInvGroup>();

    public virtual ICollection<AccessionInvGroupMap> AccessionInvGroupMapCreatedByNavigations { get; set; } = new List<AccessionInvGroupMap>();

    public virtual ICollection<AccessionInvGroupMap> AccessionInvGroupMapModifiedByNavigations { get; set; } = new List<AccessionInvGroupMap>();

    public virtual ICollection<AccessionInvGroupMap> AccessionInvGroupMapOwnedByNavigations { get; set; } = new List<AccessionInvGroupMap>();

    public virtual ICollection<AccessionInvGroup> AccessionInvGroupModifiedByNavigations { get; set; } = new List<AccessionInvGroup>();

    public virtual ICollection<AccessionInvGroup> AccessionInvGroupOwnedByNavigations { get; set; } = new List<AccessionInvGroup>();

    public virtual ICollection<AccessionInvName> AccessionInvNameCreatedByNavigations { get; set; } = new List<AccessionInvName>();

    public virtual ICollection<AccessionInvName> AccessionInvNameModifiedByNavigations { get; set; } = new List<AccessionInvName>();

    public virtual ICollection<AccessionInvName> AccessionInvNameNameSourceCooperators { get; set; } = new List<AccessionInvName>();

    public virtual ICollection<AccessionInvName> AccessionInvNameOwnedByNavigations { get; set; } = new List<AccessionInvName>();

    public virtual ICollection<AccessionInvVoucher> AccessionInvVoucherCollectorCooperators { get; set; } = new List<AccessionInvVoucher>();

    public virtual ICollection<AccessionInvVoucher> AccessionInvVoucherCreatedByNavigations { get; set; } = new List<AccessionInvVoucher>();

    public virtual ICollection<AccessionInvVoucher> AccessionInvVoucherModifiedByNavigations { get; set; } = new List<AccessionInvVoucher>();

    public virtual ICollection<AccessionInvVoucher> AccessionInvVoucherOwnedByNavigations { get; set; } = new List<AccessionInvVoucher>();

    public virtual ICollection<AccessionIpr> AccessionIprCooperators { get; set; } = new List<AccessionIpr>();

    public virtual ICollection<AccessionIpr> AccessionIprCreatedByNavigations { get; set; } = new List<AccessionIpr>();

    public virtual ICollection<AccessionIpr> AccessionIprModifiedByNavigations { get; set; } = new List<AccessionIpr>();

    public virtual ICollection<AccessionIpr> AccessionIprOwnedByNavigations { get; set; } = new List<AccessionIpr>();

    public virtual ICollection<Accession> AccessionModifiedByNavigations { get; set; } = new List<Accession>();

    public virtual ICollection<Accession> AccessionOwnedByNavigations { get; set; } = new List<Accession>();

    public virtual ICollection<AccessionPedigree> AccessionPedigreeCreatedByNavigations { get; set; } = new List<AccessionPedigree>();

    public virtual ICollection<AccessionPedigree> AccessionPedigreeModifiedByNavigations { get; set; } = new List<AccessionPedigree>();

    public virtual ICollection<AccessionPedigree> AccessionPedigreeOwnedByNavigations { get; set; } = new List<AccessionPedigree>();

    public virtual ICollection<AccessionQuarantine> AccessionQuarantineCreatedByNavigations { get; set; } = new List<AccessionQuarantine>();

    public virtual ICollection<AccessionQuarantine> AccessionQuarantineCustodialCooperators { get; set; } = new List<AccessionQuarantine>();

    public virtual ICollection<AccessionQuarantine> AccessionQuarantineModifiedByNavigations { get; set; } = new List<AccessionQuarantine>();

    public virtual ICollection<AccessionQuarantine> AccessionQuarantineOwnedByNavigations { get; set; } = new List<AccessionQuarantine>();

    public virtual ICollection<AccessionSource> AccessionSourceCreatedByNavigations { get; set; } = new List<AccessionSource>();

    public virtual ICollection<AccessionSourceMap> AccessionSourceMapCooperators { get; set; } = new List<AccessionSourceMap>();

    public virtual ICollection<AccessionSourceMap> AccessionSourceMapCreatedByNavigations { get; set; } = new List<AccessionSourceMap>();

    public virtual ICollection<AccessionSourceMap> AccessionSourceMapModifiedByNavigations { get; set; } = new List<AccessionSourceMap>();

    public virtual ICollection<AccessionSourceMap> AccessionSourceMapOwnedByNavigations { get; set; } = new List<AccessionSourceMap>();

    public virtual ICollection<AccessionSource> AccessionSourceModifiedByNavigations { get; set; } = new List<AccessionSource>();

    public virtual ICollection<AccessionSource> AccessionSourceOwnedByNavigations { get; set; } = new List<AccessionSource>();

    public virtual ICollection<AppUserItemList> AppUserItemListCooperators { get; set; } = new List<AppUserItemList>();

    public virtual ICollection<AppUserItemList> AppUserItemListCreatedByNavigations { get; set; } = new List<AppUserItemList>();

    public virtual ICollection<AppUserItemList> AppUserItemListModifiedByNavigations { get; set; } = new List<AppUserItemList>();

    public virtual ICollection<AppUserItemList> AppUserItemListOwnedByNavigations { get; set; } = new List<AppUserItemList>();

    public virtual ICollection<Citation> CitationCreatedByNavigations { get; set; } = new List<Citation>();

    public virtual ICollection<Citation> CitationModifiedByNavigations { get; set; } = new List<Citation>();

    public virtual ICollection<Citation> CitationOwnedByNavigations { get; set; } = new List<Citation>();

    public virtual ICollection<CodeValue> CodeValueCreatedByNavigations { get; set; } = new List<CodeValue>();

    public virtual ICollection<CodeValueLang> CodeValueLangCreatedByNavigations { get; set; } = new List<CodeValueLang>();

    public virtual ICollection<CodeValueLang> CodeValueLangModifiedByNavigations { get; set; } = new List<CodeValueLang>();

    public virtual ICollection<CodeValueLang> CodeValueLangOwnedByNavigations { get; set; } = new List<CodeValueLang>();

    public virtual ICollection<CodeValue> CodeValueModifiedByNavigations { get; set; } = new List<CodeValue>();

    public virtual ICollection<CodeValue> CodeValueOwnedByNavigations { get; set; } = new List<CodeValue>();

    public virtual ICollection<CooperatorAttach> CooperatorAttachAttachCooperators { get; set; } = new List<CooperatorAttach>();

    public virtual ICollection<CooperatorAttach> CooperatorAttachCreatedByNavigations { get; set; } = new List<CooperatorAttach>();

    public virtual ICollection<CooperatorAttach> CooperatorAttachModifiedByNavigations { get; set; } = new List<CooperatorAttach>();

    public virtual ICollection<CooperatorAttach> CooperatorAttachOwnedByNavigations { get; set; } = new List<CooperatorAttach>();

    public virtual ICollection<CooperatorGroup> CooperatorGroupCreatedByNavigations { get; set; } = new List<CooperatorGroup>();

    public virtual ICollection<CooperatorGroup> CooperatorGroupModifiedByNavigations { get; set; } = new List<CooperatorGroup>();

    public virtual ICollection<CooperatorGroup> CooperatorGroupOwnedByNavigations { get; set; } = new List<CooperatorGroup>();

    public virtual ICollection<CooperatorMap> CooperatorMapCooperators { get; set; } = new List<CooperatorMap>();

    public virtual ICollection<CooperatorMap> CooperatorMapCreatedByNavigations { get; set; } = new List<CooperatorMap>();

    public virtual ICollection<CooperatorMap> CooperatorMapModifiedByNavigations { get; set; } = new List<CooperatorMap>();

    public virtual ICollection<CooperatorMap> CooperatorMapOwnedByNavigations { get; set; } = new List<CooperatorMap>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<CropAttach> CropAttachAttachCooperators { get; set; } = new List<CropAttach>();

    public virtual ICollection<CropAttach> CropAttachCreatedByNavigations { get; set; } = new List<CropAttach>();

    public virtual ICollection<CropAttach> CropAttachModifiedByNavigations { get; set; } = new List<CropAttach>();

    public virtual ICollection<CropAttach> CropAttachOwnedByNavigations { get; set; } = new List<CropAttach>();

    public virtual ICollection<Crop> CropCreatedByNavigations { get; set; } = new List<Crop>();

    public virtual ICollection<Crop> CropModifiedByNavigations { get; set; } = new List<Crop>();

    public virtual ICollection<Crop> CropOwnedByNavigations { get; set; } = new List<Crop>();

    public virtual ICollection<CropTraitAttach> CropTraitAttachAttachCooperators { get; set; } = new List<CropTraitAttach>();

    public virtual ICollection<CropTraitAttach> CropTraitAttachCreatedByNavigations { get; set; } = new List<CropTraitAttach>();

    public virtual ICollection<CropTraitAttach> CropTraitAttachModifiedByNavigations { get; set; } = new List<CropTraitAttach>();

    public virtual ICollection<CropTraitAttach> CropTraitAttachOwnedByNavigations { get; set; } = new List<CropTraitAttach>();

    public virtual ICollection<CropTraitCodeAttach> CropTraitCodeAttachAttachCooperators { get; set; } = new List<CropTraitCodeAttach>();

    public virtual ICollection<CropTraitCodeAttach> CropTraitCodeAttachCreatedByNavigations { get; set; } = new List<CropTraitCodeAttach>();

    public virtual ICollection<CropTraitCodeAttach> CropTraitCodeAttachModifiedByNavigations { get; set; } = new List<CropTraitCodeAttach>();

    public virtual ICollection<CropTraitCodeAttach> CropTraitCodeAttachOwnedByNavigations { get; set; } = new List<CropTraitCodeAttach>();

    public virtual ICollection<CropTraitCode> CropTraitCodeCreatedByNavigations { get; set; } = new List<CropTraitCode>();

    public virtual ICollection<CropTraitCodeLang> CropTraitCodeLangCreatedByNavigations { get; set; } = new List<CropTraitCodeLang>();

    public virtual ICollection<CropTraitCodeLang> CropTraitCodeLangModifiedByNavigations { get; set; } = new List<CropTraitCodeLang>();

    public virtual ICollection<CropTraitCodeLang> CropTraitCodeLangOwnedByNavigations { get; set; } = new List<CropTraitCodeLang>();

    public virtual ICollection<CropTraitCode> CropTraitCodeModifiedByNavigations { get; set; } = new List<CropTraitCode>();

    public virtual ICollection<CropTraitCode> CropTraitCodeOwnedByNavigations { get; set; } = new List<CropTraitCode>();

    public virtual ICollection<CropTrait> CropTraitCreatedByNavigations { get; set; } = new List<CropTrait>();

    public virtual ICollection<CropTraitLang> CropTraitLangCreatedByNavigations { get; set; } = new List<CropTraitLang>();

    public virtual ICollection<CropTraitLang> CropTraitLangModifiedByNavigations { get; set; } = new List<CropTraitLang>();

    public virtual ICollection<CropTraitLang> CropTraitLangOwnedByNavigations { get; set; } = new List<CropTraitLang>();

    public virtual ICollection<CropTrait> CropTraitModifiedByNavigations { get; set; } = new List<CropTrait>();

    public virtual ICollection<CropTraitObservation> CropTraitObservationCreatedByNavigations { get; set; } = new List<CropTraitObservation>();

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationDatumCreatedByNavigations { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationDatumModifiedByNavigations { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationDatumOwnedByNavigations { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservation> CropTraitObservationModifiedByNavigations { get; set; } = new List<CropTraitObservation>();

    public virtual ICollection<CropTraitObservation> CropTraitObservationOwnedByNavigations { get; set; } = new List<CropTraitObservation>();

    public virtual ICollection<CropTrait> CropTraitOwnedByNavigations { get; set; } = new List<CropTrait>();

    public virtual Cooperator CurrentCooperator { get; set; }

    public virtual ICollection<EmailAttach> EmailAttachCreatedByNavigations { get; set; } = new List<EmailAttach>();

    public virtual ICollection<EmailAttach> EmailAttachModifiedByNavigations { get; set; } = new List<EmailAttach>();

    public virtual ICollection<EmailAttach> EmailAttachOwnedByNavigations { get; set; } = new List<EmailAttach>();

    public virtual ICollection<Email> EmailCreatedByNavigations { get; set; } = new List<Email>();

    public virtual ICollection<Email> EmailModifiedByNavigations { get; set; } = new List<Email>();

    public virtual ICollection<Email> EmailOwnedByNavigations { get; set; } = new List<Email>();

    public virtual ICollection<EmailTemplate> EmailTemplateCreatedByNavigations { get; set; } = new List<EmailTemplate>();

    public virtual ICollection<EmailTemplate> EmailTemplateModifiedByNavigations { get; set; } = new List<EmailTemplate>();

    public virtual ICollection<EmailTemplate> EmailTemplateOwnedByNavigations { get; set; } = new List<EmailTemplate>();

    public virtual ICollection<Exploration> ExplorationCreatedByNavigations { get; set; } = new List<Exploration>();

    public virtual ICollection<Exploration> ExplorationHostCooperators { get; set; } = new List<Exploration>();

    public virtual ICollection<ExplorationMap> ExplorationMapCooperators { get; set; } = new List<ExplorationMap>();

    public virtual ICollection<ExplorationMap> ExplorationMapCreatedByNavigations { get; set; } = new List<ExplorationMap>();

    public virtual ICollection<ExplorationMap> ExplorationMapModifiedByNavigations { get; set; } = new List<ExplorationMap>();

    public virtual ICollection<ExplorationMap> ExplorationMapOwnedByNavigations { get; set; } = new List<ExplorationMap>();

    public virtual ICollection<Exploration> ExplorationModifiedByNavigations { get; set; } = new List<Exploration>();

    public virtual ICollection<Exploration> ExplorationOwnedByNavigations { get; set; } = new List<Exploration>();

    public virtual ICollection<Feedback> FeedbackCreatedByNavigations { get; set; } = new List<Feedback>();

    public virtual ICollection<FeedbackForm> FeedbackFormCreatedByNavigations { get; set; } = new List<FeedbackForm>();

    public virtual ICollection<FeedbackFormField> FeedbackFormFieldCreatedByNavigations { get; set; } = new List<FeedbackFormField>();

    public virtual ICollection<FeedbackFormField> FeedbackFormFieldModifiedByNavigations { get; set; } = new List<FeedbackFormField>();

    public virtual ICollection<FeedbackFormField> FeedbackFormFieldOwnedByNavigations { get; set; } = new List<FeedbackFormField>();

    public virtual ICollection<FeedbackForm> FeedbackFormModifiedByNavigations { get; set; } = new List<FeedbackForm>();

    public virtual ICollection<FeedbackForm> FeedbackFormOwnedByNavigations { get; set; } = new List<FeedbackForm>();

    public virtual ICollection<FeedbackFormTrait> FeedbackFormTraitCreatedByNavigations { get; set; } = new List<FeedbackFormTrait>();

    public virtual ICollection<FeedbackFormTrait> FeedbackFormTraitModifiedByNavigations { get; set; } = new List<FeedbackFormTrait>();

    public virtual ICollection<FeedbackFormTrait> FeedbackFormTraitOwnedByNavigations { get; set; } = new List<FeedbackFormTrait>();

    public virtual ICollection<FeedbackInventory> FeedbackInventoryCreatedByNavigations { get; set; } = new List<FeedbackInventory>();

    public virtual ICollection<FeedbackInventory> FeedbackInventoryModifiedByNavigations { get; set; } = new List<FeedbackInventory>();

    public virtual ICollection<FeedbackInventory> FeedbackInventoryOwnedByNavigations { get; set; } = new List<FeedbackInventory>();

    public virtual ICollection<Feedback> FeedbackModifiedByNavigations { get; set; } = new List<Feedback>();

    public virtual ICollection<Feedback> FeedbackOwnedByNavigations { get; set; } = new List<Feedback>();

    public virtual ICollection<FeedbackReportAttach> FeedbackReportAttachCreatedByNavigations { get; set; } = new List<FeedbackReportAttach>();

    public virtual ICollection<FeedbackReportAttach> FeedbackReportAttachModifiedByNavigations { get; set; } = new List<FeedbackReportAttach>();

    public virtual ICollection<FeedbackReportAttach> FeedbackReportAttachOwnedByNavigations { get; set; } = new List<FeedbackReportAttach>();

    public virtual ICollection<FeedbackReport> FeedbackReportCreatedByNavigations { get; set; } = new List<FeedbackReport>();

    public virtual ICollection<FeedbackReport> FeedbackReportModifiedByNavigations { get; set; } = new List<FeedbackReport>();

    public virtual ICollection<FeedbackReport> FeedbackReportOwnedByNavigations { get; set; } = new List<FeedbackReport>();

    public virtual ICollection<FeedbackResultAttach> FeedbackResultAttachCreatedByNavigations { get; set; } = new List<FeedbackResultAttach>();

    public virtual ICollection<FeedbackResultAttach> FeedbackResultAttachModifiedByNavigations { get; set; } = new List<FeedbackResultAttach>();

    public virtual ICollection<FeedbackResultAttach> FeedbackResultAttachOwnedByNavigations { get; set; } = new List<FeedbackResultAttach>();

    public virtual ICollection<FeedbackResult> FeedbackResultCreatedByNavigations { get; set; } = new List<FeedbackResult>();

    public virtual ICollection<FeedbackResultField> FeedbackResultFieldCreatedByNavigations { get; set; } = new List<FeedbackResultField>();

    public virtual ICollection<FeedbackResultField> FeedbackResultFieldModifiedByNavigations { get; set; } = new List<FeedbackResultField>();

    public virtual ICollection<FeedbackResultField> FeedbackResultFieldOwnedByNavigations { get; set; } = new List<FeedbackResultField>();

    public virtual ICollection<FeedbackResultGroup> FeedbackResultGroupCreatedByNavigations { get; set; } = new List<FeedbackResultGroup>();

    public virtual ICollection<FeedbackResultGroup> FeedbackResultGroupModifiedByNavigations { get; set; } = new List<FeedbackResultGroup>();

    public virtual ICollection<FeedbackResultGroup> FeedbackResultGroupOwnedByNavigations { get; set; } = new List<FeedbackResultGroup>();

    public virtual ICollection<FeedbackResult> FeedbackResultModifiedByNavigations { get; set; } = new List<FeedbackResult>();

    public virtual ICollection<FeedbackResult> FeedbackResultOwnedByNavigations { get; set; } = new List<FeedbackResult>();

    public virtual ICollection<FeedbackResultTraitOb> FeedbackResultTraitObCreatedByNavigations { get; set; } = new List<FeedbackResultTraitOb>();

    public virtual ICollection<FeedbackResultTraitOb> FeedbackResultTraitObModifiedByNavigations { get; set; } = new List<FeedbackResultTraitOb>();

    public virtual ICollection<FeedbackResultTraitOb> FeedbackResultTraitObOwnedByNavigations { get; set; } = new List<FeedbackResultTraitOb>();

    public virtual ICollection<GeneticAnnotation> GeneticAnnotationCreatedByNavigations { get; set; } = new List<GeneticAnnotation>();

    public virtual ICollection<GeneticAnnotation> GeneticAnnotationModifiedByNavigations { get; set; } = new List<GeneticAnnotation>();

    public virtual ICollection<GeneticAnnotation> GeneticAnnotationOwnedByNavigations { get; set; } = new List<GeneticAnnotation>();

    public virtual ICollection<GeneticMarker> GeneticMarkerCreatedByNavigations { get; set; } = new List<GeneticMarker>();

    public virtual ICollection<GeneticMarker> GeneticMarkerModifiedByNavigations { get; set; } = new List<GeneticMarker>();

    public virtual ICollection<GeneticMarker> GeneticMarkerOwnedByNavigations { get; set; } = new List<GeneticMarker>();

    public virtual ICollection<GeneticObservation> GeneticObservationCreatedByNavigations { get; set; } = new List<GeneticObservation>();

    public virtual ICollection<GeneticObservationDatum> GeneticObservationDatumCreatedByNavigations { get; set; } = new List<GeneticObservationDatum>();

    public virtual ICollection<GeneticObservationDatum> GeneticObservationDatumModifiedByNavigations { get; set; } = new List<GeneticObservationDatum>();

    public virtual ICollection<GeneticObservationDatum> GeneticObservationDatumOwnedByNavigations { get; set; } = new List<GeneticObservationDatum>();

    public virtual ICollection<GeneticObservation> GeneticObservationModifiedByNavigations { get; set; } = new List<GeneticObservation>();

    public virtual ICollection<GeneticObservation> GeneticObservationOwnedByNavigations { get; set; } = new List<GeneticObservation>();

    public virtual ICollection<GenevaSiteInventory> GenevaSiteInventoryCreatedByNavigations { get; set; } = new List<GenevaSiteInventory>();

    public virtual ICollection<GenevaSiteInventory> GenevaSiteInventoryModifiedByNavigations { get; set; } = new List<GenevaSiteInventory>();

    public virtual ICollection<GenevaSiteInventory> GenevaSiteInventoryOwnedByNavigations { get; set; } = new List<GenevaSiteInventory>();

    public virtual Geography Geography { get; set; }

    public virtual ICollection<Geography> GeographyCreatedByNavigations { get; set; } = new List<Geography>();

    public virtual ICollection<Geography> GeographyModifiedByNavigations { get; set; } = new List<Geography>();

    public virtual ICollection<Geography> GeographyOwnedByNavigations { get; set; } = new List<Geography>();

    public virtual ICollection<GeographyRegionMap> GeographyRegionMapCreatedByNavigations { get; set; } = new List<GeographyRegionMap>();

    public virtual ICollection<GeographyRegionMap> GeographyRegionMapModifiedByNavigations { get; set; } = new List<GeographyRegionMap>();

    public virtual ICollection<GeographyRegionMap> GeographyRegionMapOwnedByNavigations { get; set; } = new List<GeographyRegionMap>();

    public virtual ICollection<GspiSiteInventory> GspiSiteInventoryCreatedByNavigations { get; set; } = new List<GspiSiteInventory>();

    public virtual ICollection<GspiSiteInventory> GspiSiteInventoryModifiedByNavigations { get; set; } = new List<GspiSiteInventory>();

    public virtual ICollection<GspiSiteInventory> GspiSiteInventoryOwnedByNavigations { get; set; } = new List<GspiSiteInventory>();

    public virtual ICollection<InventoryAction> InventoryActionCooperators { get; set; } = new List<InventoryAction>();

    public virtual ICollection<InventoryAction> InventoryActionCreatedByNavigations { get; set; } = new List<InventoryAction>();

    public virtual ICollection<InventoryAction> InventoryActionModifiedByNavigations { get; set; } = new List<InventoryAction>();

    public virtual ICollection<InventoryAction> InventoryActionOwnedByNavigations { get; set; } = new List<InventoryAction>();

    public virtual ICollection<Inventory> InventoryCreatedByNavigations { get; set; } = new List<Inventory>();

    public virtual ICollection<InventoryMaintPolicy> InventoryMaintPolicyCreatedByNavigations { get; set; } = new List<InventoryMaintPolicy>();

    public virtual ICollection<InventoryMaintPolicy> InventoryMaintPolicyCuratorCooperators { get; set; } = new List<InventoryMaintPolicy>();

    public virtual ICollection<InventoryMaintPolicy> InventoryMaintPolicyModifiedByNavigations { get; set; } = new List<InventoryMaintPolicy>();

    public virtual ICollection<InventoryMaintPolicy> InventoryMaintPolicyOwnedByNavigations { get; set; } = new List<InventoryMaintPolicy>();

    public virtual ICollection<InventoryMaintPolicySeason> InventoryMaintPolicySeasonCreatedByNavigations { get; set; } = new List<InventoryMaintPolicySeason>();

    public virtual ICollection<InventoryMaintPolicySeason> InventoryMaintPolicySeasonModifiedByNavigations { get; set; } = new List<InventoryMaintPolicySeason>();

    public virtual ICollection<InventoryMaintPolicySeason> InventoryMaintPolicySeasonOwnedByNavigations { get; set; } = new List<InventoryMaintPolicySeason>();

    public virtual ICollection<Inventory> InventoryModifiedByNavigations { get; set; } = new List<Inventory>();

    public virtual ICollection<Inventory> InventoryOwnedByNavigations { get; set; } = new List<Inventory>();

    public virtual ICollection<InventoryQualityStatus> InventoryQualityStatusCreatedByNavigations { get; set; } = new List<InventoryQualityStatus>();

    public virtual ICollection<InventoryQualityStatus> InventoryQualityStatusModifiedByNavigations { get; set; } = new List<InventoryQualityStatus>();

    public virtual ICollection<InventoryQualityStatus> InventoryQualityStatusOwnedByNavigations { get; set; } = new List<InventoryQualityStatus>();

    public virtual ICollection<InventoryQualityStatus> InventoryQualityStatusTesterCooperators { get; set; } = new List<InventoryQualityStatus>();

    public virtual ICollection<InventoryViability> InventoryViabilityCreatedByNavigations { get; set; } = new List<InventoryViability>();

    public virtual ICollection<InventoryViabilityDatum> InventoryViabilityDatumCounterCooperators { get; set; } = new List<InventoryViabilityDatum>();

    public virtual ICollection<InventoryViabilityDatum> InventoryViabilityDatumCreatedByNavigations { get; set; } = new List<InventoryViabilityDatum>();

    public virtual ICollection<InventoryViabilityDatum> InventoryViabilityDatumModifiedByNavigations { get; set; } = new List<InventoryViabilityDatum>();

    public virtual ICollection<InventoryViabilityDatum> InventoryViabilityDatumOwnedByNavigations { get; set; } = new List<InventoryViabilityDatum>();

    public virtual ICollection<InventoryViability> InventoryViabilityModifiedByNavigations { get; set; } = new List<InventoryViability>();

    public virtual ICollection<InventoryViability> InventoryViabilityOwnedByNavigations { get; set; } = new List<InventoryViability>();

    public virtual ICollection<InventoryViabilityRule> InventoryViabilityRuleCreatedByNavigations { get; set; } = new List<InventoryViabilityRule>();

    public virtual ICollection<InventoryViabilityRuleMap> InventoryViabilityRuleMapCreatedByNavigations { get; set; } = new List<InventoryViabilityRuleMap>();

    public virtual ICollection<InventoryViabilityRuleMap> InventoryViabilityRuleMapModifiedByNavigations { get; set; } = new List<InventoryViabilityRuleMap>();

    public virtual ICollection<InventoryViabilityRuleMap> InventoryViabilityRuleMapOwnedByNavigations { get; set; } = new List<InventoryViabilityRuleMap>();

    public virtual ICollection<InventoryViabilityRule> InventoryViabilityRuleModifiedByNavigations { get; set; } = new List<InventoryViabilityRule>();

    public virtual ICollection<InventoryViabilityRule> InventoryViabilityRuleOwnedByNavigations { get; set; } = new List<InventoryViabilityRule>();

    public virtual ICollection<Cooperator> InverseCreatedByNavigation { get; set; } = new List<Cooperator>();

    public virtual ICollection<Cooperator> InverseCurrentCooperator { get; set; } = new List<Cooperator>();

    public virtual ICollection<Cooperator> InverseModifiedByNavigation { get; set; } = new List<Cooperator>();

    public virtual ICollection<Cooperator> InverseOwnedByNavigation { get; set; } = new List<Cooperator>();

    public virtual ICollection<Literature> LiteratureCreatedByNavigations { get; set; } = new List<Literature>();

    public virtual ICollection<Literature> LiteratureModifiedByNavigations { get; set; } = new List<Literature>();

    public virtual ICollection<Literature> LiteratureOwnedByNavigations { get; set; } = new List<Literature>();

    public virtual ICollection<MethodAttach> MethodAttachAttachCooperators { get; set; } = new List<MethodAttach>();

    public virtual ICollection<MethodAttach> MethodAttachCreatedByNavigations { get; set; } = new List<MethodAttach>();

    public virtual ICollection<MethodAttach> MethodAttachModifiedByNavigations { get; set; } = new List<MethodAttach>();

    public virtual ICollection<MethodAttach> MethodAttachOwnedByNavigations { get; set; } = new List<MethodAttach>();

    public virtual ICollection<Method> MethodCreatedByNavigations { get; set; } = new List<Method>();

    public virtual ICollection<MethodMap> MethodMapCooperators { get; set; } = new List<MethodMap>();

    public virtual ICollection<MethodMap> MethodMapCreatedByNavigations { get; set; } = new List<MethodMap>();

    public virtual ICollection<MethodMap> MethodMapModifiedByNavigations { get; set; } = new List<MethodMap>();

    public virtual ICollection<MethodMap> MethodMapOwnedByNavigations { get; set; } = new List<MethodMap>();

    public virtual ICollection<Method> MethodModifiedByNavigations { get; set; } = new List<Method>();

    public virtual ICollection<Method> MethodOwnedByNavigations { get; set; } = new List<Method>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual ICollection<NameGroup> NameGroupCreatedByNavigations { get; set; } = new List<NameGroup>();

    public virtual ICollection<NameGroup> NameGroupModifiedByNavigations { get; set; } = new List<NameGroup>();

    public virtual ICollection<NameGroup> NameGroupOwnedByNavigations { get; set; } = new List<NameGroup>();

    public virtual ICollection<Nc7InventoryLocationDatum> Nc7InventoryLocationDatumCooperators { get; set; } = new List<Nc7InventoryLocationDatum>();

    public virtual ICollection<Nc7InventoryLocationDatum> Nc7InventoryLocationDatumCreatedByNavigations { get; set; } = new List<Nc7InventoryLocationDatum>();

    public virtual ICollection<Nc7InventoryLocationDatum> Nc7InventoryLocationDatumModifiedByNavigations { get; set; } = new List<Nc7InventoryLocationDatum>();

    public virtual ICollection<Nc7InventoryLocationDatum> Nc7InventoryLocationDatumOwnedByNavigations { get; set; } = new List<Nc7InventoryLocationDatum>();

    public virtual ICollection<Nc7SiteInventory> Nc7SiteInventoryCreatedByNavigations { get; set; } = new List<Nc7SiteInventory>();

    public virtual ICollection<Nc7SiteInventory> Nc7SiteInventoryModifiedByNavigations { get; set; } = new List<Nc7SiteInventory>();

    public virtual ICollection<Nc7SiteInventory> Nc7SiteInventoryOwnedByNavigations { get; set; } = new List<Nc7SiteInventory>();

    public virtual ICollection<Ne9SiteInventory> Ne9SiteInventoryCreatedByNavigations { get; set; } = new List<Ne9SiteInventory>();

    public virtual ICollection<Ne9SiteInventory> Ne9SiteInventoryModifiedByNavigations { get; set; } = new List<Ne9SiteInventory>();

    public virtual ICollection<Ne9SiteInventory> Ne9SiteInventoryOwnedByNavigations { get; set; } = new List<Ne9SiteInventory>();

    public virtual ICollection<NsslSiteInventory> NsslSiteInventoryCreatedByNavigations { get; set; } = new List<NsslSiteInventory>();

    public virtual ICollection<NsslSiteInventory> NsslSiteInventoryModifiedByNavigations { get; set; } = new List<NsslSiteInventory>();

    public virtual ICollection<NsslSiteInventory> NsslSiteInventoryOwnedByNavigations { get; set; } = new List<NsslSiteInventory>();

    public virtual ICollection<OpgcSiteInventory> OpgcSiteInventoryCreatedByNavigations { get; set; } = new List<OpgcSiteInventory>();

    public virtual ICollection<OpgcSiteInventory> OpgcSiteInventoryModifiedByNavigations { get; set; } = new List<OpgcSiteInventory>();

    public virtual ICollection<OpgcSiteInventory> OpgcSiteInventoryOwnedByNavigations { get; set; } = new List<OpgcSiteInventory>();

    public virtual ICollection<OrderRequestAction> OrderRequestActionCooperators { get; set; } = new List<OrderRequestAction>();

    public virtual ICollection<OrderRequestAction> OrderRequestActionCreatedByNavigations { get; set; } = new List<OrderRequestAction>();

    public virtual ICollection<OrderRequestAction> OrderRequestActionModifiedByNavigations { get; set; } = new List<OrderRequestAction>();

    public virtual ICollection<OrderRequestAction> OrderRequestActionOwnedByNavigations { get; set; } = new List<OrderRequestAction>();

    public virtual ICollection<OrderRequestAttach> OrderRequestAttachAttachCooperators { get; set; } = new List<OrderRequestAttach>();

    public virtual ICollection<OrderRequestAttach> OrderRequestAttachCreatedByNavigations { get; set; } = new List<OrderRequestAttach>();

    public virtual ICollection<OrderRequestAttach> OrderRequestAttachModifiedByNavigations { get; set; } = new List<OrderRequestAttach>();

    public virtual ICollection<OrderRequestAttach> OrderRequestAttachOwnedByNavigations { get; set; } = new List<OrderRequestAttach>();

    public virtual ICollection<OrderRequest> OrderRequestCreatedByNavigations { get; set; } = new List<OrderRequest>();

    public virtual ICollection<OrderRequest> OrderRequestFinalRecipientCooperators { get; set; } = new List<OrderRequest>();

    public virtual ICollection<OrderRequestItemAction> OrderRequestItemActionCooperators { get; set; } = new List<OrderRequestItemAction>();

    public virtual ICollection<OrderRequestItemAction> OrderRequestItemActionCreatedByNavigations { get; set; } = new List<OrderRequestItemAction>();

    public virtual ICollection<OrderRequestItemAction> OrderRequestItemActionModifiedByNavigations { get; set; } = new List<OrderRequestItemAction>();

    public virtual ICollection<OrderRequestItemAction> OrderRequestItemActionOwnedByNavigations { get; set; } = new List<OrderRequestItemAction>();

    public virtual ICollection<OrderRequestItem> OrderRequestItemCreatedByNavigations { get; set; } = new List<OrderRequestItem>();

    public virtual ICollection<OrderRequestItem> OrderRequestItemModifiedByNavigations { get; set; } = new List<OrderRequestItem>();

    public virtual ICollection<OrderRequestItem> OrderRequestItemOwnedByNavigations { get; set; } = new List<OrderRequestItem>();

    public virtual ICollection<OrderRequestItem> OrderRequestItemSourceCooperators { get; set; } = new List<OrderRequestItem>();

    public virtual ICollection<OrderRequest> OrderRequestModifiedByNavigations { get; set; } = new List<OrderRequest>();

    public virtual ICollection<OrderRequest> OrderRequestOwnedByNavigations { get; set; } = new List<OrderRequest>();

    public virtual ICollection<OrderRequestPhytoLog> OrderRequestPhytoLogCreatedByNavigations { get; set; } = new List<OrderRequestPhytoLog>();

    public virtual ICollection<OrderRequestPhytoLog> OrderRequestPhytoLogInspectedByCooperators { get; set; } = new List<OrderRequestPhytoLog>();

    public virtual ICollection<OrderRequestPhytoLog> OrderRequestPhytoLogModifiedByNavigations { get; set; } = new List<OrderRequestPhytoLog>();

    public virtual ICollection<OrderRequestPhytoLog> OrderRequestPhytoLogOwnedByNavigations { get; set; } = new List<OrderRequestPhytoLog>();

    public virtual ICollection<OrderRequest> OrderRequestRequestorCooperators { get; set; } = new List<OrderRequest>();

    public virtual ICollection<OrderRequest> OrderRequestShipToCooperators { get; set; } = new List<OrderRequest>();

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<ParlSiteInventory> ParlSiteInventoryCreatedByNavigations { get; set; } = new List<ParlSiteInventory>();

    public virtual ICollection<ParlSiteInventory> ParlSiteInventoryModifiedByNavigations { get; set; } = new List<ParlSiteInventory>();

    public virtual ICollection<ParlSiteInventory> ParlSiteInventoryOwnedByNavigations { get; set; } = new List<ParlSiteInventory>();

    public virtual ICollection<Region> RegionCreatedByNavigations { get; set; } = new List<Region>();

    public virtual ICollection<Region> RegionModifiedByNavigations { get; set; } = new List<Region>();

    public virtual ICollection<Region> RegionOwnedByNavigations { get; set; } = new List<Region>();

    public virtual ICollection<S9SiteInventory> S9SiteInventoryCreatedByNavigations { get; set; } = new List<S9SiteInventory>();

    public virtual ICollection<S9SiteInventory> S9SiteInventoryModifiedByNavigations { get; set; } = new List<S9SiteInventory>();

    public virtual ICollection<S9SiteInventory> S9SiteInventoryOwnedByNavigations { get; set; } = new List<S9SiteInventory>();

    public virtual Geography SecondaryGeography { get; set; }

    public virtual Site Site { get; set; }

    public virtual ICollection<Site> SiteCreatedByNavigations { get; set; } = new List<Site>();

    public virtual ICollection<Site> SiteModifiedByNavigations { get; set; } = new List<Site>();

    public virtual ICollection<Site> SiteOwnedByNavigations { get; set; } = new List<Site>();

    public virtual ICollection<SourceDescObservation> SourceDescObservationCreatedByNavigations { get; set; } = new List<SourceDescObservation>();

    public virtual ICollection<SourceDescObservation> SourceDescObservationModifiedByNavigations { get; set; } = new List<SourceDescObservation>();

    public virtual ICollection<SourceDescObservation> SourceDescObservationOwnedByNavigations { get; set; } = new List<SourceDescObservation>();

    public virtual ICollection<SourceDescriptorCode> SourceDescriptorCodeCreatedByNavigations { get; set; } = new List<SourceDescriptorCode>();

    public virtual ICollection<SourceDescriptorCodeLang> SourceDescriptorCodeLangCreatedByNavigations { get; set; } = new List<SourceDescriptorCodeLang>();

    public virtual ICollection<SourceDescriptorCodeLang> SourceDescriptorCodeLangModifiedByNavigations { get; set; } = new List<SourceDescriptorCodeLang>();

    public virtual ICollection<SourceDescriptorCodeLang> SourceDescriptorCodeLangOwnedByNavigations { get; set; } = new List<SourceDescriptorCodeLang>();

    public virtual ICollection<SourceDescriptorCode> SourceDescriptorCodeModifiedByNavigations { get; set; } = new List<SourceDescriptorCode>();

    public virtual ICollection<SourceDescriptorCode> SourceDescriptorCodeOwnedByNavigations { get; set; } = new List<SourceDescriptorCode>();

    public virtual ICollection<SourceDescriptor> SourceDescriptorCreatedByNavigations { get; set; } = new List<SourceDescriptor>();

    public virtual ICollection<SourceDescriptorLang> SourceDescriptorLangCreatedByNavigations { get; set; } = new List<SourceDescriptorLang>();

    public virtual ICollection<SourceDescriptorLang> SourceDescriptorLangModifiedByNavigations { get; set; } = new List<SourceDescriptorLang>();

    public virtual ICollection<SourceDescriptorLang> SourceDescriptorLangOwnedByNavigations { get; set; } = new List<SourceDescriptorLang>();

    public virtual ICollection<SourceDescriptor> SourceDescriptorModifiedByNavigations { get; set; } = new List<SourceDescriptor>();

    public virtual ICollection<SourceDescriptor> SourceDescriptorOwnedByNavigations { get; set; } = new List<SourceDescriptor>();

    public virtual ICollection<SysFile> SysFileCreatedByNavigations { get; set; } = new List<SysFile>();

    public virtual ICollection<SysFileGroup> SysFileGroupCreatedByNavigations { get; set; } = new List<SysFileGroup>();

    public virtual ICollection<SysFileGroupMap> SysFileGroupMapCreatedByNavigations { get; set; } = new List<SysFileGroupMap>();

    public virtual ICollection<SysFileGroupMap> SysFileGroupMapModifiedByNavigations { get; set; } = new List<SysFileGroupMap>();

    public virtual ICollection<SysFileGroupMap> SysFileGroupMapOwnedByNavigations { get; set; } = new List<SysFileGroupMap>();

    public virtual ICollection<SysFileGroup> SysFileGroupModifiedByNavigations { get; set; } = new List<SysFileGroup>();

    public virtual ICollection<SysFileGroup> SysFileGroupOwnedByNavigations { get; set; } = new List<SysFileGroup>();

    public virtual ICollection<SysFileLang> SysFileLangCreatedByNavigations { get; set; } = new List<SysFileLang>();

    public virtual ICollection<SysFileLang> SysFileLangModifiedByNavigations { get; set; } = new List<SysFileLang>();

    public virtual ICollection<SysFileLang> SysFileLangOwnedByNavigations { get; set; } = new List<SysFileLang>();

    public virtual ICollection<SysFile> SysFileModifiedByNavigations { get; set; } = new List<SysFile>();

    public virtual ICollection<SysFile> SysFileOwnedByNavigations { get; set; } = new List<SysFile>();

    public virtual ICollection<SysGroup> SysGroupCreatedByNavigations { get; set; } = new List<SysGroup>();

    public virtual ICollection<SysGroupLang> SysGroupLangCreatedByNavigations { get; set; } = new List<SysGroupLang>();

    public virtual ICollection<SysGroupLang> SysGroupLangModifiedByNavigations { get; set; } = new List<SysGroupLang>();

    public virtual ICollection<SysGroupLang> SysGroupLangOwnedByNavigations { get; set; } = new List<SysGroupLang>();

    public virtual ICollection<SysGroup> SysGroupModifiedByNavigations { get; set; } = new List<SysGroup>();

    public virtual ICollection<SysGroup> SysGroupOwnedByNavigations { get; set; } = new List<SysGroup>();

    public virtual ICollection<SysGroupPermissionMap> SysGroupPermissionMapCreatedByNavigations { get; set; } = new List<SysGroupPermissionMap>();

    public virtual ICollection<SysGroupPermissionMap> SysGroupPermissionMapModifiedByNavigations { get; set; } = new List<SysGroupPermissionMap>();

    public virtual ICollection<SysGroupPermissionMap> SysGroupPermissionMapOwnedByNavigations { get; set; } = new List<SysGroupPermissionMap>();

    public virtual ICollection<SysGroupUserMap> SysGroupUserMapCreatedByNavigations { get; set; } = new List<SysGroupUserMap>();

    public virtual ICollection<SysGroupUserMap> SysGroupUserMapModifiedByNavigations { get; set; } = new List<SysGroupUserMap>();

    public virtual ICollection<SysGroupUserMap> SysGroupUserMapOwnedByNavigations { get; set; } = new List<SysGroupUserMap>();

    public virtual ICollection<SysIndex> SysIndexCreatedByNavigations { get; set; } = new List<SysIndex>();

    public virtual ICollection<SysIndexField> SysIndexFieldCreatedByNavigations { get; set; } = new List<SysIndexField>();

    public virtual ICollection<SysIndexField> SysIndexFieldModifiedByNavigations { get; set; } = new List<SysIndexField>();

    public virtual ICollection<SysIndexField> SysIndexFieldOwnedByNavigations { get; set; } = new List<SysIndexField>();

    public virtual ICollection<SysIndex> SysIndexModifiedByNavigations { get; set; } = new List<SysIndex>();

    public virtual ICollection<SysIndex> SysIndexOwnedByNavigations { get; set; } = new List<SysIndex>();

    public virtual SysLang SysLang { get; set; }

    public virtual ICollection<SysLang> SysLangCreatedByNavigations { get; set; } = new List<SysLang>();

    public virtual ICollection<SysLang> SysLangModifiedByNavigations { get; set; } = new List<SysLang>();

    public virtual ICollection<SysLang> SysLangOwnedByNavigations { get; set; } = new List<SysLang>();

    public virtual ICollection<SysPermission> SysPermissionCreatedByNavigations { get; set; } = new List<SysPermission>();

    public virtual ICollection<SysPermissionField> SysPermissionFieldCreatedByNavigations { get; set; } = new List<SysPermissionField>();

    public virtual ICollection<SysPermissionField> SysPermissionFieldModifiedByNavigations { get; set; } = new List<SysPermissionField>();

    public virtual ICollection<SysPermissionField> SysPermissionFieldOwnedByNavigations { get; set; } = new List<SysPermissionField>();

    public virtual ICollection<SysPermissionLang> SysPermissionLangCreatedByNavigations { get; set; } = new List<SysPermissionLang>();

    public virtual ICollection<SysPermissionLang> SysPermissionLangModifiedByNavigations { get; set; } = new List<SysPermissionLang>();

    public virtual ICollection<SysPermissionLang> SysPermissionLangOwnedByNavigations { get; set; } = new List<SysPermissionLang>();

    public virtual ICollection<SysPermission> SysPermissionModifiedByNavigations { get; set; } = new List<SysPermission>();

    public virtual ICollection<SysPermission> SysPermissionOwnedByNavigations { get; set; } = new List<SysPermission>();

    public virtual ICollection<SysSearchAutofield> SysSearchAutofieldCreatedByNavigations { get; set; } = new List<SysSearchAutofield>();

    public virtual ICollection<SysSearchAutofield> SysSearchAutofieldModifiedByNavigations { get; set; } = new List<SysSearchAutofield>();

    public virtual ICollection<SysSearchAutofield> SysSearchAutofieldOwnedByNavigations { get; set; } = new List<SysSearchAutofield>();

    public virtual ICollection<SysSearchResolver> SysSearchResolverCreatedByNavigations { get; set; } = new List<SysSearchResolver>();

    public virtual ICollection<SysSearchResolver> SysSearchResolverModifiedByNavigations { get; set; } = new List<SysSearchResolver>();

    public virtual ICollection<SysSearchResolver> SysSearchResolverOwnedByNavigations { get; set; } = new List<SysSearchResolver>();

    public virtual ICollection<SysTable> SysTableCreatedByNavigations { get; set; } = new List<SysTable>();

    public virtual ICollection<SysTableField> SysTableFieldCreatedByNavigations { get; set; } = new List<SysTableField>();

    public virtual ICollection<SysTableFieldLang> SysTableFieldLangCreatedByNavigations { get; set; } = new List<SysTableFieldLang>();

    public virtual ICollection<SysTableFieldLang> SysTableFieldLangModifiedByNavigations { get; set; } = new List<SysTableFieldLang>();

    public virtual ICollection<SysTableFieldLang> SysTableFieldLangOwnedByNavigations { get; set; } = new List<SysTableFieldLang>();

    public virtual ICollection<SysTableField> SysTableFieldModifiedByNavigations { get; set; } = new List<SysTableField>();

    public virtual ICollection<SysTableField> SysTableFieldOwnedByNavigations { get; set; } = new List<SysTableField>();

    public virtual ICollection<SysTableLang> SysTableLangCreatedByNavigations { get; set; } = new List<SysTableLang>();

    public virtual ICollection<SysTableLang> SysTableLangModifiedByNavigations { get; set; } = new List<SysTableLang>();

    public virtual ICollection<SysTableLang> SysTableLangOwnedByNavigations { get; set; } = new List<SysTableLang>();

    public virtual ICollection<SysTable> SysTableModifiedByNavigations { get; set; } = new List<SysTable>();

    public virtual ICollection<SysTable> SysTableOwnedByNavigations { get; set; } = new List<SysTable>();

    public virtual ICollection<SysTableRelationship> SysTableRelationshipCreatedByNavigations { get; set; } = new List<SysTableRelationship>();

    public virtual ICollection<SysTableRelationship> SysTableRelationshipModifiedByNavigations { get; set; } = new List<SysTableRelationship>();

    public virtual ICollection<SysTableRelationship> SysTableRelationshipOwnedByNavigations { get; set; } = new List<SysTableRelationship>();

    public virtual ICollection<SysUser> SysUserCooperators { get; set; } = new List<SysUser>();

    public virtual ICollection<SysUser> SysUserCreatedByNavigations { get; set; } = new List<SysUser>();

    public virtual ICollection<SysUser> SysUserModifiedByNavigations { get; set; } = new List<SysUser>();

    public virtual ICollection<SysUser> SysUserOwnedByNavigations { get; set; } = new List<SysUser>();

    public virtual ICollection<SysUserPermissionMap> SysUserPermissionMapCreatedByNavigations { get; set; } = new List<SysUserPermissionMap>();

    public virtual ICollection<SysUserPermissionMap> SysUserPermissionMapModifiedByNavigations { get; set; } = new List<SysUserPermissionMap>();

    public virtual ICollection<SysUserPermissionMap> SysUserPermissionMapOwnedByNavigations { get; set; } = new List<SysUserPermissionMap>();

    public virtual ICollection<W6SiteInventory> W6SiteInventoryCreatedByNavigations { get; set; } = new List<W6SiteInventory>();

    public virtual ICollection<W6SiteInventory> W6SiteInventoryModifiedByNavigations { get; set; } = new List<W6SiteInventory>();

    public virtual ICollection<W6SiteInventory> W6SiteInventoryOwnedByNavigations { get; set; } = new List<W6SiteInventory>();

    public virtual WebCooperator WebCooperator { get; set; }

    public virtual ICollection<WebHelp> WebHelpCreatedByNavigations { get; set; } = new List<WebHelp>();

    public virtual ICollection<WebHelp> WebHelpModifiedByNavigations { get; set; } = new List<WebHelp>();

    public virtual ICollection<WebHelp> WebHelpOwnedByNavigations { get; set; } = new List<WebHelp>();
}