// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CountryView
{
    public int GeographyId { get; set; }

    public string CountryCode { get; set; }

    public string Countryname { get; set; }
}