// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CropGermplasmCommitteeDocument
{
    public int CropGermplasmCommitteeDocumentId { get; set; }

    public int? CropGermplasmCommitteeId { get; set; }

    public string Url { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public string Title { get; set; }

    public string CategoryCode { get; set; }

    public string DocumentTitle { get; set; }

    public int? DocumentYear { get; set; }
}