// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CropGermplasmCommitteeCropDescriptor
{
    public int CropGermplasmCommitteeId { get; set; }

    public int CropId { get; set; }
}