// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CropTraitCode
{
    public int CropTraitCodeId { get; set; }

    public int CropTraitId { get; set; }

    public string Code { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual CropTrait CropTrait { get; set; }

    public virtual ICollection<CropTraitCodeAttach> CropTraitCodeAttaches { get; set; } = new List<CropTraitCodeAttach>();

    public virtual ICollection<CropTraitCodeLang> CropTraitCodeLangs { get; set; } = new List<CropTraitCodeLang>();

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationData { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservation> CropTraitObservations { get; set; } = new List<CropTraitObservation>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}