// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Crop
{
    public int CropId { get; set; }

    public string Name { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<CropAttach> CropAttaches { get; set; } = new List<CropAttach>();

    public virtual ICollection<CropTrait> CropTraits { get; set; } = new List<CropTrait>();

    public virtual ICollection<GeneticMarker> GeneticMarkers { get; set; } = new List<GeneticMarker>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}