// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CropTrait
{
    public int CropTraitId { get; set; }

    public int CropId { get; set; }

    public string CodedName { get; set; }

    public string IsPeerReviewed { get; set; }

    public string CategoryCode { get; set; }

    public string DataTypeCode { get; set; }

    public string IsCoded { get; set; }

    public int? MaxLength { get; set; }

    public string NumericFormat { get; set; }

    public decimal? NumericMaximum { get; set; }

    public decimal? NumericMinimum { get; set; }

    public string OriginalValueTypeCode { get; set; }

    public string OriginalValueFormat { get; set; }

    public string IsArchived { get; set; }

    public string OntologyUrl { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Crop Crop { get; set; }

    public virtual ICollection<CropTraitAttach> CropTraitAttaches { get; set; } = new List<CropTraitAttach>();

    public virtual ICollection<CropTraitCode> CropTraitCodes { get; set; } = new List<CropTraitCode>();

    public virtual ICollection<CropTraitLang> CropTraitLangs { get; set; } = new List<CropTraitLang>();

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationData { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservation> CropTraitObservations { get; set; } = new List<CropTraitObservation>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}