// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class CropTraitObservationDatum
{
    public int CropTraitObservationDataId { get; set; }

    public int? CropTraitObservationId { get; set; }

    public int InventoryId { get; set; }

    public int Individual { get; set; }

    public int? CropTraitId { get; set; }

    public int? CropTraitCodeId { get; set; }

    public decimal? NumericValue { get; set; }

    public string StringValue { get; set; }

    public int MethodId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual CropTrait CropTrait { get; set; }

    public virtual CropTraitCode CropTraitCode { get; set; }

    public virtual CropTraitObservation CropTraitObservation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Method Method { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}