// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class EmailTemplate
{
    public int EmailTemplateId { get; set; }

    public string Title { get; set; }

    public string CategoryCode { get; set; }

    public string EmailFrom { get; set; }

    public string EmailTo { get; set; }

    public string EmailCc { get; set; }

    public string EmailBcc { get; set; }

    public string EmailReplyTo { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public string IsHtml { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string ActionCode { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}