// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Email
{
    public int EmailId { get; set; }

    public string IdType { get; set; }

    public int? IdNumber { get; set; }

    public string EmailFrom { get; set; }

    public string EmailTo { get; set; }

    public string EmailCc { get; set; }

    public string EmailBcc { get; set; }

    public string EmailReplyTo { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public string IsHtml { get; set; }

    public DateTime ToBeSentDate { get; set; }

    public DateTime? SentDate { get; set; }

    public int RetryCount { get; set; }

    public DateTime? LastRetryDate { get; set; }

    public string LastRetryErrorMessage { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<EmailAttach> EmailAttaches { get; set; } = new List<EmailAttach>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}