// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Exploration
{
    public int ExplorationId { get; set; }

    public string ExplorationNumber { get; set; }

    public string Title { get; set; }

    public DateTime? BeganDate { get; set; }

    public DateTime? FinishedDate { get; set; }

    public string FundingSource { get; set; }

    public decimal? FundingAmount { get; set; }

    public string TargetSpecies { get; set; }

    public string Permits { get; set; }

    public string Restrictions { get; set; }

    public int? FiscalYear { get; set; }

    public int? HostCooperatorId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<ExplorationMap> ExplorationMaps { get; set; } = new List<ExplorationMap>();

    public virtual Cooperator HostCooperator { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}