// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class FeedbackReport
{
    public int FeedbackReportId { get; set; }

    public int FeedbackId { get; set; }

    public int FeedbackFormId { get; set; }

    public string Title { get; set; }

    public string IsObservationData { get; set; }

    public string IsWebVisible { get; set; }

    public int DueInterval { get; set; }

    public string IntervalLengthCode { get; set; }

    public string IntervalTypeCode { get; set; }

    public DateTime? CustomDueDate { get; set; }

    public int SortOrder { get; set; }

    public string IsNotifiedInitially { get; set; }

    public string IsNotified30daysPrior { get; set; }

    public string IsNotified15daysPrior { get; set; }

    public string InitialEmailText { get; set; }

    public string InitialEmailSubject { get; set; }

    public string Prior30EmailText { get; set; }

    public string Prior30EmailSubject { get; set; }

    public string Prior15EmailText { get; set; }

    public string Prior15EmailSubject { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Feedback Feedback { get; set; }

    public virtual FeedbackForm FeedbackForm { get; set; }

    public virtual ICollection<FeedbackReportAttach> FeedbackReportAttaches { get; set; } = new List<FeedbackReportAttach>();

    public virtual ICollection<FeedbackResultGroup> FeedbackResultGroups { get; set; } = new List<FeedbackResultGroup>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}