// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class FeedbackResult
{
    public int FeedbackResultId { get; set; }

    public int FeedbackResultGroupId { get; set; }

    public int InventoryId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<FeedbackResultAttach> FeedbackResultAttaches { get; set; } = new List<FeedbackResultAttach>();

    public virtual ICollection<FeedbackResultField> FeedbackResultFields { get; set; } = new List<FeedbackResultField>();

    public virtual FeedbackResultGroup FeedbackResultGroup { get; set; }

    public virtual ICollection<FeedbackResultTraitOb> FeedbackResultTraitObs { get; set; } = new List<FeedbackResultTraitOb>();

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}