// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class FeedbackResultField
{
    public int FeedbackResultFieldId { get; set; }

    public int FeedbackResultId { get; set; }

    public int FeedbackFormFieldId { get; set; }

    public string StringValue { get; set; }

    public string AdminValue { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual FeedbackFormField FeedbackFormField { get; set; }

    public virtual FeedbackResult FeedbackResult { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}