// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class FeedbackForm
{
    public int FeedbackFormId { get; set; }

    public string Title { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<FeedbackFormField> FeedbackFormFields { get; set; } = new List<FeedbackFormField>();

    public virtual ICollection<FeedbackFormTrait> FeedbackFormTraits { get; set; } = new List<FeedbackFormTrait>();

    public virtual ICollection<FeedbackReport> FeedbackReports { get; set; } = new List<FeedbackReport>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}