// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public string Title { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string IsRestrictedByInventory { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<FeedbackAttach> FeedbackAttaches { get; set; } = new List<FeedbackAttach>();

    public virtual ICollection<FeedbackInventory> FeedbackInventories { get; set; } = new List<FeedbackInventory>();

    public virtual ICollection<FeedbackReport> FeedbackReports { get; set; } = new List<FeedbackReport>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual ICollection<OrderRequest> OrderRequests { get; set; } = new List<OrderRequest>();

    public virtual Cooperator OwnedByNavigation { get; set; }
}