// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class GeneticObservationDatum
{
    public int GeneticObservationDataId { get; set; }

    public int? GeneticObservationId { get; set; }

    public int GeneticAnnotationId { get; set; }

    public int InventoryId { get; set; }

    public int? Individual { get; set; }

    public int? IndividualAlleleNumber { get; set; }

    public string Value { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual GeneticAnnotation GeneticAnnotation { get; set; }

    public virtual GeneticObservation GeneticObservation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}