// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class GeneticObservation
{
    public int GeneticObservationId { get; set; }

    public int InventoryId { get; set; }

    public int? GeneticAnnotationId { get; set; }

    public string IsArchived { get; set; }

    public string DataQualityCode { get; set; }

    public decimal? Frequency { get; set; }

    public string Value { get; set; }

    public int? Rank { get; set; }

    public decimal? MeanValue { get; set; }

    public decimal? MaximumValue { get; set; }

    public decimal? MinimumValue { get; set; }

    public decimal? StandardDeviation { get; set; }

    public int? SampleSize { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual GeneticAnnotation GeneticAnnotation { get; set; }

    public virtual ICollection<GeneticObservationDatum> GeneticObservationData { get; set; } = new List<GeneticObservationDatum>();

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}