// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class GeneticMarker
{
    public int GeneticMarkerId { get; set; }

    public int CropId { get; set; }

    public string Name { get; set; }

    public string Synonyms { get; set; }

    public string RepeatMotif { get; set; }

    public string Primers { get; set; }

    public string AssayConditions { get; set; }

    public string RangeProducts { get; set; }

    public string GenbankNumber { get; set; }

    public string KnownStandards { get; set; }

    public string MapLocation { get; set; }

    public string Position { get; set; }

    public string PolyTypeCode { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Crop Crop { get; set; }

    public virtual ICollection<GeneticAnnotation> GeneticAnnotations { get; set; } = new List<GeneticAnnotation>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}