// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class GeneticAnnotation
{
    public int GeneticAnnotationId { get; set; }

    public int GeneticMarkerId { get; set; }

    public int MethodId { get; set; }

    public string AssayMethod { get; set; }

    public string ScoringMethod { get; set; }

    public string ControlValues { get; set; }

    public int? ObservationAllelesCount { get; set; }

    public int? MaxGobAlleles { get; set; }

    public string SizeAlleles { get; set; }

    public string UnusualAlleles { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual GeneticMarker GeneticMarker { get; set; }

    public virtual ICollection<GeneticObservationDatum> GeneticObservationData { get; set; } = new List<GeneticObservationDatum>();

    public virtual ICollection<GeneticObservation> GeneticObservations { get; set; } = new List<GeneticObservation>();

    public virtual Method Method { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}