// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class GspiSiteInventory
{
    public int GspiSiteInventoryId { get; set; }

    public int InventoryId { get; set; }

    public int? SeedQuantity { get; set; }

    public string SeedAge { get; set; }

    public decimal? HundredWeight { get; set; }

    public string IncreaseLocation { get; set; }

    public string IncreaseYear { get; set; }

    public string LotTypeCode { get; set; }

    public string PollenVectorCode { get; set; }

    public string PollenEnvironment { get; set; }

    public string PollenProcedureCode { get; set; }

    public int? SplitInventoryId { get; set; }

    public string Plot { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual Inventory SplitInventory { get; set; }
}