// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Inventory
{
    public int InventoryId { get; set; }

    public string InventoryNumberPart1 { get; set; }

    public int? InventoryNumberPart2 { get; set; }

    public string InventoryNumberPart3 { get; set; }

    public string FormTypeCode { get; set; }

    public int InventoryMaintPolicyId { get; set; }

    public string IsDistributable { get; set; }

    public string StorageLocationPart1 { get; set; }

    public string StorageLocationPart2 { get; set; }

    public string StorageLocationPart3 { get; set; }

    public string StorageLocationPart4 { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string IsAvailable { get; set; }

    public string WebAvailabilityNote { get; set; }

    public string AvailabilityStatusCode { get; set; }

    public string AvailabilityStatusNote { get; set; }

    public DateTime? AvailabilityStartDate { get; set; }

    public DateTime? AvailabilityEndDate { get; set; }

    public decimal? QuantityOnHand { get; set; }

    public string QuantityOnHandUnitCode { get; set; }

    public string IsAutoDeducted { get; set; }

    public string DistributionDefaultFormCode { get; set; }

    public decimal? DistributionDefaultQuantity { get; set; }

    public string DistributionUnitCode { get; set; }

    public decimal? DistributionCriticalQuantity { get; set; }

    public decimal? RegenerationCriticalQuantity { get; set; }

    public string PathogenStatusCode { get; set; }

    public int AccessionId { get; set; }

    public int? ParentInventoryId { get; set; }

    public int? BackupInventoryId { get; set; }

    public string Rootstock { get; set; }

    public decimal? HundredSeedWeight { get; set; }

    public string PollinationMethodCode { get; set; }

    public string PollinationVectorCode { get; set; }

    public int? PreservationMethodId { get; set; }

    public int? RegenerationMethodId { get; set; }

    public string PlantSexCode { get; set; }

    public DateTime? PropagationDate { get; set; }

    public string PropagationDateCode { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string DigitalObjectIdentifier { get; set; }

    public string PropagationTechniqueCode { get; set; }

    public string Doi { get; set; }

    public int? ProductionLocationGeographyId { get; set; }

    public string InventoryIdString { get; set; }

    public virtual Accession Accession { get; set; }

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotations { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<AccessionInvAttach> AccessionInvAttaches { get; set; } = new List<AccessionInvAttach>();

    public virtual ICollection<AccessionInvGroupMap> AccessionInvGroupMaps { get; set; } = new List<AccessionInvGroupMap>();

    public virtual ICollection<AccessionInvName> AccessionInvNames { get; set; } = new List<AccessionInvName>();

    public virtual ICollection<AccessionInvVoucher> AccessionInvVouchers { get; set; } = new List<AccessionInvVoucher>();

    public virtual Inventory BackupInventory { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationData { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservation> CropTraitObservations { get; set; } = new List<CropTraitObservation>();

    public virtual ICollection<FeedbackInventory> FeedbackInventories { get; set; } = new List<FeedbackInventory>();

    public virtual ICollection<FeedbackResultTraitOb> FeedbackResultTraitObs { get; set; } = new List<FeedbackResultTraitOb>();

    public virtual ICollection<FeedbackResult> FeedbackResults { get; set; } = new List<FeedbackResult>();

    public virtual ICollection<GeneticObservationDatum> GeneticObservationData { get; set; } = new List<GeneticObservationDatum>();

    public virtual ICollection<GeneticObservation> GeneticObservations { get; set; } = new List<GeneticObservation>();

    public virtual GenevaSiteInventory GenevaSiteInventory { get; set; }

    public virtual GspiSiteInventory GspiSiteInventoryInventory { get; set; }

    public virtual ICollection<GspiSiteInventory> GspiSiteInventorySplitInventories { get; set; } = new List<GspiSiteInventory>();

    public virtual ICollection<InventoryAction> InventoryActions { get; set; } = new List<InventoryAction>();

    public virtual InventoryMaintPolicy InventoryMaintPolicy { get; set; }

    public virtual ICollection<InventoryQualityStatus> InventoryQualityStatuses { get; set; } = new List<InventoryQualityStatus>();

    public virtual ICollection<InventoryViability> InventoryViabilities { get; set; } = new List<InventoryViability>();

    public virtual ICollection<Inventory> InverseBackupInventory { get; set; } = new List<Inventory>();

    public virtual ICollection<Inventory> InverseParentInventory { get; set; } = new List<Inventory>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual ICollection<Nc7InventoryLocationDatum> Nc7InventoryLocationData { get; set; } = new List<Nc7InventoryLocationDatum>();

    public virtual Nc7SiteInventory Nc7SiteInventory { get; set; }

    public virtual Ne9SiteInventory Ne9SiteInventory { get; set; }

    public virtual NsslSiteInventory NsslSiteInventory { get; set; }

    public virtual OpgcSiteInventory OpgcSiteInventory { get; set; }

    public virtual ICollection<OrderRequestItem> OrderRequestItems { get; set; } = new List<OrderRequestItem>();

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual Inventory ParentInventory { get; set; }

    public virtual ParlSiteInventory ParlSiteInventory { get; set; }

    public virtual Method PreservationMethod { get; set; }

    public virtual Geography ProductionLocationGeography { get; set; }

    public virtual Method RegenerationMethod { get; set; }

    public virtual S9SiteInventory S9SiteInventory { get; set; }

    public virtual W6SiteInventory W6SiteInventoryInventory { get; set; }

    public virtual ICollection<W6SiteInventory> W6SiteInventorySplitInventories { get; set; } = new List<W6SiteInventory>();

    public virtual ICollection<WebOrderRequestItem> WebOrderRequestItems { get; set; } = new List<WebOrderRequestItem>();

    public virtual ICollection<WebUserCartItem> WebUserCartItems { get; set; } = new List<WebUserCartItem>();
}