// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class InventoryViability
{
    public int InventoryViabilityId { get; set; }

    public int InventoryId { get; set; }

    public int? InventoryViabilityRuleId { get; set; }

    public DateTime TestedDate { get; set; }

    public string TestedDateCode { get; set; }

    public int? PercentNormal { get; set; }

    public int? PercentAbnormal { get; set; }

    public int? PercentDormant { get; set; }

    public int? PercentViable { get; set; }

    public int? PercentHard { get; set; }

    public int? PercentEmpty { get; set; }

    public int? PercentInfested { get; set; }

    public int? PercentDead { get; set; }

    public int? PercentUnknown { get; set; }

    public string VigorRatingCode { get; set; }

    public int? TotalTestedCount { get; set; }

    public int? ReplicationCount { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<InventoryViabilityDatum> InventoryViabilityData { get; set; } = new List<InventoryViabilityDatum>();

    public virtual InventoryViabilityRule InventoryViabilityRule { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}