// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class InventoryViabilityDatum
{
    public int InventoryViabilityDataId { get; set; }

    public int InventoryViabilityId { get; set; }

    public int? OrderRequestItemId { get; set; }

    public int? CounterCooperatorId { get; set; }

    public int ReplicationNumber { get; set; }

    public int CountNumber { get; set; }

    public DateTime CountDate { get; set; }

    public int NormalCount { get; set; }

    public int? AbnormalCount { get; set; }

    public int? DormantCount { get; set; }

    public int? HardCount { get; set; }

    public int? EmptyCount { get; set; }

    public int? InfestedCount { get; set; }

    public int? DeadCount { get; set; }

    public int? UnknownCount { get; set; }

    public int? EstimatedDormantCount { get; set; }

    public int? TreatedDormantCount { get; set; }

    public int? ConfirmedDormantCount { get; set; }

    public int? ReplicationCount { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CounterCooperator { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual InventoryViability InventoryViability { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual OrderRequestItem OrderRequestItem { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}