// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class InventoryMaintPolicy
{
    public int InventoryMaintPolicyId { get; set; }

    public string MaintenanceName { get; set; }

    public string FormTypeCode { get; set; }

    public string QuantityOnHandUnitCode { get; set; }

    public string WebAvailabilityNote { get; set; }

    public string IsAutoDeducted { get; set; }

    public string DistributionDefaultFormCode { get; set; }

    public decimal? DistributionDefaultQuantity { get; set; }

    public string DistributionUnitCode { get; set; }

    public decimal? DistributionCriticalQuantity { get; set; }

    public decimal? RegenerationCriticalQuantity { get; set; }

    public string RegenerationMethodCode { get; set; }

    public int? CuratorCooperatorId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator CuratorCooperator { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<InventoryMaintPolicySeason> InventoryMaintPolicySeasons { get; set; } = new List<InventoryMaintPolicySeason>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}