// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class InventoryAction
{
    public int InventoryActionId { get; set; }

    public int InventoryId { get; set; }

    public string ActionNameCode { get; set; }

    public DateTime? StartedDate { get; set; }

    public string StartedDateCode { get; set; }

    public DateTime? CompletedDate { get; set; }

    public string CompletedDateCode { get; set; }

    public decimal? Quantity { get; set; }

    public string QuantityUnitCode { get; set; }

    public string FormCode { get; set; }

    public int? CooperatorId { get; set; }

    public int? MethodId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator Cooperator { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Method Method { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}