// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class InventoryViabilityRule
{
    public int InventoryViabilityRuleId { get; set; }

    public string Name { get; set; }

    public string Substrata { get; set; }

    public int? SeedsPerReplicate { get; set; }

    public int? NumberOfReplicates { get; set; }

    public string Requirements { get; set; }

    public string CategoryCode { get; set; }

    public string TemperatureRange { get; set; }

    public string CountRegimeDays { get; set; }

    public string Moisture { get; set; }

    public string Prechill { get; set; }

    public string Lighting { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<InventoryViability> InventoryViabilities { get; set; } = new List<InventoryViability>();

    public virtual ICollection<InventoryViabilityRuleMap> InventoryViabilityRuleMaps { get; set; } = new List<InventoryViabilityRuleMap>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}