// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Literature
{
    public int LiteratureId { get; set; }

    public string Abbreviation { get; set; }

    public string StandardAbbreviation { get; set; }

    public string ReferenceTitle { get; set; }

    public string EditorAuthorName { get; set; }

    public string LiteratureTypeCode { get; set; }

    public string PublicationYear { get; set; }

    public string PublisherName { get; set; }

    public string PublisherLocation { get; set; }

    public string Url { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}