// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Method
{
    public int MethodId { get; set; }

    public string Name { get; set; }

    public int? GeographyId { get; set; }

    public int? ElevationMeters { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public int? Uncertainty { get; set; }

    public string FormattedLocality { get; set; }

    public string GeoreferenceDatum { get; set; }

    public string GeoreferenceProtocolCode { get; set; }

    public string GeoreferenceAnnotation { get; set; }

    public string MaterialsAndMethods { get; set; }

    public string StudyReasonCode { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual ICollection<AccessionAction> AccessionActions { get; set; } = new List<AccessionAction>();

    public virtual ICollection<AccessionInvGroup> AccessionInvGroups { get; set; } = new List<AccessionInvGroup>();

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<CropTraitObservationDatum> CropTraitObservationData { get; set; } = new List<CropTraitObservationDatum>();

    public virtual ICollection<CropTraitObservation> CropTraitObservations { get; set; } = new List<CropTraitObservation>();

    public virtual ICollection<GeneticAnnotation> GeneticAnnotations { get; set; } = new List<GeneticAnnotation>();

    public virtual Geography Geography { get; set; }

    public virtual ICollection<InventoryAction> InventoryActions { get; set; } = new List<InventoryAction>();

    public virtual ICollection<Inventory> InventoryPreservationMethods { get; set; } = new List<Inventory>();

    public virtual ICollection<InventoryQualityStatus> InventoryQualityStatuses { get; set; } = new List<InventoryQualityStatus>();

    public virtual ICollection<Inventory> InventoryRegenerationMethods { get; set; } = new List<Inventory>();

    public virtual ICollection<MethodAttach> MethodAttaches { get; set; } = new List<MethodAttach>();

    public virtual ICollection<MethodMap> MethodMaps { get; set; } = new List<MethodMap>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual ICollection<Nc7InventoryLocationDatum> Nc7InventoryLocationData { get; set; } = new List<Nc7InventoryLocationDatum>();

    public virtual Cooperator OwnedByNavigation { get; set; }
}