// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Nc7InventoryLocationDatum
{
    public int Nc7InventoryLocationDataId { get; set; }

    public int InventoryId { get; set; }

    public string DataDateCode { get; set; }

    public DateTime? DataDate { get; set; }

    public int? DataDateNumber { get; set; }

    public int? LocationNumber { get; set; }

    public string LocationString { get; set; }

    public int? SublocationNumber { get; set; }

    public string SublocationString { get; set; }

    public string DataType1Code { get; set; }

    public string DataType2Code { get; set; }

    public string DataType3Code { get; set; }

    public string DataType4Code { get; set; }

    public decimal? NumericValue { get; set; }

    public string StringValue { get; set; }

    public string GridLocationCode { get; set; }

    public int? GridLocationX { get; set; }

    public int? GridLocationY { get; set; }

    public int? CooperatorId { get; set; }

    public int? MethodId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator Cooperator { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Method Method { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}