// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Nc7SiteInventory
{
    public int Nc7SiteInventoryId { get; set; }

    public int InventoryId { get; set; }

    public decimal? HundredWeight { get; set; }

    public string PollinationControlCode { get; set; }

    public string FarmFieldIdentifierCode { get; set; }

    public string LocationTypeCode { get; set; }

    public string LocationLow { get; set; }

    public string LocationHigh { get; set; }

    public string SublocationTypeCode { get; set; }

    public string SublocationLow { get; set; }

    public string SublocationHigh { get; set; }

    public string OldInventoryIdentifier { get; set; }

    public string InventorySiteNote { get; set; }

    public decimal? InventoryLocation1Latitude { get; set; }

    public decimal? InventoryLocation1Longitude { get; set; }

    public int? InventoryLocation1Precision { get; set; }

    public decimal? InventoryLocation2Latitude { get; set; }

    public decimal? InventoryLocation2Longitude { get; set; }

    public int? InventoryLocation2Precision { get; set; }

    public string InventoryDatumCode { get; set; }

    public string CoordinatesApplyToCode { get; set; }

    public string CoordinatesComment { get; set; }

    public string CoordinatesVoucherLocation { get; set; }

    public string IrregularInventoryLocation { get; set; }

    public string IsIncreaseSuccessFlag { get; set; }

    public string ReasonUnsuccessfull1Code { get; set; }

    public string ReasonUnsuccessfull2Code { get; set; }

    public string ReasonUnsuccessfull3Code { get; set; }

    public string ReasonUnsuccessfullNote { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}