// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Ne9SiteInventory
{
    public int Ne9SiteInventoryId { get; set; }

    public int InventoryId { get; set; }

    public string LotTypeCode { get; set; }

    public string InventoryPurposeCode { get; set; }

    public string PollinationProcCode { get; set; }

    public string PollinationVectorCode { get; set; }

    public string PollinationEnvCode { get; set; }

    public decimal? HundredWeight { get; set; }

    public string Parent2 { get; set; }

    public string Parent3 { get; set; }

    public string Parent4 { get; set; }

    public string Parent5 { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}