// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class NsslSiteInventory
{
    public int NsslSiteInventoryId { get; set; }

    public int InventoryId { get; set; }

    public string NextTest { get; set; }

    public decimal? HundredWeight { get; set; }

    public decimal? Moisture1 { get; set; }

    public string Moisture1TypeCode { get; set; }

    public DateTime? Moisture1Date { get; set; }

    public decimal? Moisture2 { get; set; }

    public string Moisture2TypeCode { get; set; }

    public DateTime? Moisture2Date { get; set; }

    public decimal? Moisture3 { get; set; }

    public string Moisture3TypeCode { get; set; }

    public DateTime? Moisture3Date { get; set; }

    public decimal? Moisture4 { get; set; }

    public string Moisture4TypeCode { get; set; }

    public DateTime? Moisture4Date { get; set; }

    public decimal? Moisture5 { get; set; }

    public string Moisture5TypeCode { get; set; }

    public DateTime? Moisture5Date { get; set; }

    public decimal? PercentCleanout { get; set; }

    public int? EstimatedInLn2 { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public int? ShootsPerVial { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}