// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class OpgcSiteInventory
{
    public int OpgcSiteInventoryId { get; set; }

    public int InventoryId { get; set; }

    public decimal? HundredWeight { get; set; }

    public string LocationCode { get; set; }

    public string LocationTypeCode { get; set; }

    public string OldInventoryIdentifier { get; set; }

    public string FarmFieldIdentifierCode { get; set; }

    public int? CageGreenhouse { get; set; }

    public string TechniqueCode { get; set; }

    public string PollinationControlCode { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}