// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class OrderRequest
{
    public int OrderRequestId { get; set; }

    public int? OriginalOrderRequestId { get; set; }

    public int? WebOrderRequestId { get; set; }

    public string LocalNumber { get; set; }

    public string OrderTypeCode { get; set; }

    public DateTime? OrderedDate { get; set; }

    public string IntendedUseCode { get; set; }

    public string IntendedUseNote { get; set; }

    public DateTime? CompletedDate { get; set; }

    public int? RequestorCooperatorId { get; set; }

    public int? ShipToCooperatorId { get; set; }

    public int FinalRecipientCooperatorId { get; set; }

    public string OrderObtainedVia { get; set; }

    public int? FeedbackId { get; set; }

    public string SpecialInstruction { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotations { get; set; } = new List<AccessionInvAnnotation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator FinalRecipientCooperator { get; set; }

    public virtual ICollection<OrderRequest> InverseOriginalOrderRequest { get; set; } = new List<OrderRequest>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual ICollection<OrderRequestAction> OrderRequestActions { get; set; } = new List<OrderRequestAction>();

    public virtual ICollection<OrderRequestAttach> OrderRequestAttaches { get; set; } = new List<OrderRequestAttach>();

    public virtual ICollection<OrderRequestItem> OrderRequestItems { get; set; } = new List<OrderRequestItem>();

    public virtual ICollection<OrderRequestPhytoLog> OrderRequestPhytoLogs { get; set; } = new List<OrderRequestPhytoLog>();

    public virtual OrderRequest OriginalOrderRequest { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual Cooperator RequestorCooperator { get; set; }

    public virtual Cooperator ShipToCooperator { get; set; }

    public virtual WebOrderRequest WebOrderRequest { get; set; }
}