// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class OrderRequestItem
{
    public int OrderRequestItemId { get; set; }

    public int OrderRequestId { get; set; }

    public int? WebOrderRequestItemId { get; set; }

    public int? SequenceNumber { get; set; }

    public string Name { get; set; }

    public decimal? QuantityShipped { get; set; }

    public string QuantityShippedUnitCode { get; set; }

    public string DistributionFormCode { get; set; }

    public string StatusCode { get; set; }

    public DateTime? StatusDate { get; set; }

    public int InventoryId { get; set; }

    public string ExternalTaxonomy { get; set; }

    public int? SourceCooperatorId { get; set; }

    public string Note { get; set; }

    public string WebUserNote { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string IsSmtaRestricted { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<InventoryViabilityDatum> InventoryViabilityData { get; set; } = new List<InventoryViabilityDatum>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual OrderRequest OrderRequest { get; set; }

    public virtual ICollection<OrderRequestItemAction> OrderRequestItemActions { get; set; } = new List<OrderRequestItemAction>();

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual Cooperator SourceCooperator { get; set; }

    public virtual WebOrderRequestItem WebOrderRequestItem { get; set; }
}