// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class OrderRequestPhytoLog
{
    public int OrderRequestPhytoLogId { get; set; }

    public int OrderRequestId { get; set; }

    public DateTime ReceivedDate { get; set; }

    public DateTime? OpenedDate { get; set; }

    public string NumberOfPackages { get; set; }

    public int? NumberOfItems { get; set; }

    public string MajorGenus { get; set; }

    public string ImportPermitIdentifier { get; set; }

    public DateTime? SetupInspectionDate { get; set; }

    public DateTime? InspectedDate { get; set; }

    public int? InspectedByCooperatorId { get; set; }

    public string PhytoCertificateTypeCode { get; set; }

    public int? CertificateCost { get; set; }

    public string PhytoCertificateIdentifier { get; set; }

    public DateTime? ShippedDate { get; set; }

    public string ShippingCarrier { get; set; }

    public string TrackingIdentifier { get; set; }

    public string PassedInspection { get; set; }

    public string Delivered { get; set; }

    public DateTime? DeliveredDate { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator InspectedByCooperator { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual OrderRequest OrderRequest { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}