// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class PlantInventory
{
    public int PlantInventoryId { get; set; }

    public int PlantInventoryVolumn { get; set; }

    public int PlantInventoryYear { get; set; }

    public int StartingPiNumber { get; set; }
}