// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class PlantInventoryIndex
{
    public int PlantInventoryIndexId { get; set; }

    public int PlantInventoryVolumn { get; set; }

    public int PlantInventoryPage { get; set; }

    public int FirstNumber { get; set; }

    public int LastNumber { get; set; }

    public int PageOffset { get; set; }

    public string VolumnSuffix { get; set; }
}