// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class PlantImmigrantIndex
{
    public int PlantImmigrantIndexId { get; set; }

    public int PlantImmigrantVolumn { get; set; }

    public int FirstNumber { get; set; }

    public int LastNumber { get; set; }

    public int PlantImmigrantPage { get; set; }
}