// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Region
{
    public int RegionId { get; set; }

    public string Continent { get; set; }

    public string Subcontinent { get; set; }

    public int? SequenceNumber { get; set; }

    public string ContinentAbbreviation { get; set; }

    public string SubcontinentAbbreviation { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<GeographyRegionMap> GeographyRegionMaps { get; set; } = new List<GeographyRegionMap>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}