// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Rhizobium
{
    public int RhizobiumId { get; set; }

    public string UsdaAccessionCode { get; set; }

    public string HostPlant { get; set; }

    public string CommonName { get; set; }

    public string Source { get; set; }

    public string GeoSource { get; set; }

    public string Note { get; set; }

    public string GenusSpp { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}