// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Rhy
{
    public int RhyId { get; set; }

    public int UsdaAcces { get; set; }

    public string Synonym1 { get; set; }

    public string Synonym2 { get; set; }

    public string Synonym3 { get; set; }

    public string Synonym4 { get; set; }

    public string HostPlant { get; set; }

    public string CommonNam { get; set; }

    public string Source { get; set; }

    public string GeoSource { get; set; }

    public string Serogroup { get; set; }

    public string HostsNodu { get; set; }

    public string Comments { get; set; }

    public string GenusSpp { get; set; }
}