// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class Site
{
    public int SiteId { get; set; }

    public string SiteShortName { get; set; }

    public string SiteLongName { get; set; }

    public string ProviderIdentifier { get; set; }

    public string OrganizationAbbrev { get; set; }

    public string IsInternal { get; set; }

    public string IsDistributionSite { get; set; }

    public string TypeCode { get; set; }

    public string FaoInstituteNumber { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string PrimaryUrl { get; set; }

    public string SecondaryUrl { get; set; }

    public virtual ICollection<Accession> AccessionBackupLocation1Sites { get; set; } = new List<Accession>();

    public virtual ICollection<Accession> AccessionBackupLocation2Sites { get; set; } = new List<Accession>();

    public virtual ICollection<CooperatorGroup> CooperatorGroups { get; set; } = new List<CooperatorGroup>();

    public virtual ICollection<Cooperator> Cooperators { get; set; } = new List<Cooperator>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }
}