// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SourceDescObservation
{
    public int SourceDescObservationId { get; set; }

    public int AccessionSourceId { get; set; }

    public int SourceDescriptorId { get; set; }

    public int? SourceDescriptorCodeId { get; set; }

    public decimal? NumericValue { get; set; }

    public string StringValue { get; set; }

    public string OriginalValue { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual AccessionSource AccessionSource { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual SourceDescriptor SourceDescriptor { get; set; }

    public virtual SourceDescriptorCode SourceDescriptorCode { get; set; }
}