// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysAppErrorLog
{
    public int Id { get; set; }

    public string ApplicationCode { get; set; }

    public DateTime CreateDate { get; set; }

    public string ErrorLevel { get; set; }

    public string ErrorMessage { get; set; }

    public string StackTrace { get; set; }

    public string Exception { get; set; }

    public string Logger { get; set; }

    public string Url { get; set; }
}