// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysFile
{
    public int SysFileId { get; set; }

    public string IsEnabled { get; set; }

    public string VirtualFilePath { get; set; }

    public string FileName { get; set; }

    public string FileVersion { get; set; }

    public decimal? FileSize { get; set; }

    public string DisplayName { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SysFileGroupMap> SysFileGroupMaps { get; set; } = new List<SysFileGroupMap>();

    public virtual ICollection<SysFileLang> SysFileLangs { get; set; } = new List<SysFileLang>();
}