// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysGroup
{
    public int SysGroupId { get; set; }

    public string GroupTag { get; set; }

    public string IsEnabled { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SysGroupLang> SysGroupLangs { get; set; } = new List<SysGroupLang>();

    public virtual ICollection<SysGroupPermissionMap> SysGroupPermissionMaps { get; set; } = new List<SysGroupPermissionMap>();

    public virtual ICollection<SysGroupUserMap> SysGroupUserMaps { get; set; } = new List<SysGroupUserMap>();
}