// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysLang
{
    public int SysLangId { get; set; }

    public string Iso6393Tag { get; set; }

    public string IetfTag { get; set; }

    public string ScriptDirection { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public bool? IsWebVisible { get; set; }

    public virtual ICollection<AppResource> AppResources { get; set; } = new List<AppResource>();

    public virtual ICollection<CodeValueLang> CodeValueLangs { get; set; } = new List<CodeValueLang>();

    public virtual ICollection<Cooperator> Cooperators { get; set; } = new List<Cooperator>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual ICollection<CropTraitCodeLang> CropTraitCodeLangs { get; set; } = new List<CropTraitCodeLang>();

    public virtual ICollection<CropTraitLang> CropTraitLangs { get; set; } = new List<CropTraitLang>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SourceDescriptorCodeLang> SourceDescriptorCodeLangs { get; set; } = new List<SourceDescriptorCodeLang>();

    public virtual ICollection<SourceDescriptorLang> SourceDescriptorLangs { get; set; } = new List<SourceDescriptorLang>();

    public virtual ICollection<SysFileLang> SysFileLangs { get; set; } = new List<SysFileLang>();

    public virtual ICollection<SysGroupLang> SysGroupLangs { get; set; } = new List<SysGroupLang>();

    public virtual ICollection<SysPermissionLang> SysPermissionLangs { get; set; } = new List<SysPermissionLang>();

    public virtual ICollection<SysTableFieldLang> SysTableFieldLangs { get; set; } = new List<SysTableFieldLang>();

    public virtual ICollection<SysTableLang> SysTableLangs { get; set; } = new List<SysTableLang>();

    public virtual ICollection<WebHelp> WebHelps { get; set; } = new List<WebHelp>();

    public virtual ICollection<WebUser> WebUsers { get; set; } = new List<WebUser>();
}