// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysPermission
{
    public int SysPermissionId { get; set; }

    public int? SysDataviewId { get; set; }

    public int? SysTableId { get; set; }

    public string PermissionTag { get; set; }

    public string IsEnabled { get; set; }

    public string CreatePermission { get; set; }

    public string ReadPermission { get; set; }

    public string UpdatePermission { get; set; }

    public string DeletePermission { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SysGroupPermissionMap> SysGroupPermissionMaps { get; set; } = new List<SysGroupPermissionMap>();

    public virtual ICollection<SysPermissionField> SysPermissionFields { get; set; } = new List<SysPermissionField>();

    public virtual ICollection<SysPermissionLang> SysPermissionLangs { get; set; } = new List<SysPermissionLang>();

    public virtual SysTable SysTable { get; set; }

    public virtual ICollection<SysUserPermissionMap> SysUserPermissionMaps { get; set; } = new List<SysUserPermissionMap>();
}