// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysTable
{
    public int SysTableId { get; set; }

    public string TableName { get; set; }

    public string IsEnabled { get; set; }

    public string IsReadonly { get; set; }

    public string AuditsCreated { get; set; }

    public string AuditsModified { get; set; }

    public string AuditsOwned { get; set; }

    public string DatabaseAreaCode { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SysPermission> SysPermissions { get; set; } = new List<SysPermission>();

    public virtual ICollection<SysSearchResolver> SysSearchResolvers { get; set; } = new List<SysSearchResolver>();

    public virtual ICollection<SysTableField> SysTableFields { get; set; } = new List<SysTableField>();

    public virtual ICollection<SysTableLang> SysTableLangs { get; set; } = new List<SysTableLang>();
}