// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class SysTableField
{
    public int SysTableFieldId { get; set; }

    public int SysTableId { get; set; }

    public string FieldName { get; set; }

    public int? FieldOrdinal { get; set; }

    public string FieldPurpose { get; set; }

    public string FieldType { get; set; }

    public string DefaultValue { get; set; }

    public string IsPrimaryKey { get; set; }

    public string IsForeignKey { get; set; }

    public int? ForeignKeyTableFieldId { get; set; }

    public string ForeignKeyDataviewName { get; set; }

    public string IsNullable { get; set; }

    public string GuiHint { get; set; }

    public string IsReadonly { get; set; }

    public int MinLength { get; set; }

    public int MaxLength { get; set; }

    public int NumericPrecision { get; set; }

    public int NumericScale { get; set; }

    public string IsAutoincrement { get; set; }

    public string GroupName { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual SysTableField ForeignKeyTableField { get; set; }

    public virtual ICollection<SysTableField> InverseForeignKeyTableField { get; set; } = new List<SysTableField>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<SysPermissionField> SysPermissionFieldParentTableFields { get; set; } = new List<SysPermissionField>();

    public virtual ICollection<SysPermissionField> SysPermissionFieldSysTableFields { get; set; } = new List<SysPermissionField>();

    public virtual SysTable SysTable { get; set; }

    public virtual ICollection<SysTableFieldLang> SysTableFieldLangs { get; set; } = new List<SysTableFieldLang>();

    public virtual ICollection<SysTableRelationship> SysTableRelationshipOtherTableFields { get; set; } = new List<SysTableRelationship>();

    public virtual ICollection<SysTableRelationship> SysTableRelationshipSysTableFields { get; set; } = new List<SysTableRelationship>();
}