// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class TaxonomySpecy
{
    public int TaxonomySpeciesId { get; set; }

    public int? CurrentTaxonomySpeciesId { get; set; }

    public int? NomenNumber { get; set; }

    public string IsSpecificHybrid { get; set; }

    public string SpeciesName { get; set; }

    public string SpeciesAuthority { get; set; }

    public string IsSubspecificHybrid { get; set; }

    public string SubspeciesName { get; set; }

    public string SubspeciesAuthority { get; set; }

    public string IsVarietalHybrid { get; set; }

    public string VarietyName { get; set; }

    public string VarietyAuthority { get; set; }

    public string IsSubvarietalHybrid { get; set; }

    public string SubvarietyName { get; set; }

    public string SubvarietyAuthority { get; set; }

    public string IsFormaHybrid { get; set; }

    public string FormaRankType { get; set; }

    public string FormaName { get; set; }

    public string FormaAuthority { get; set; }

    public int TaxonomyGenusId { get; set; }

    public int? Priority1SiteId { get; set; }

    public int? Priority2SiteId { get; set; }

    public int? Curator1CooperatorId { get; set; }

    public int? Curator2CooperatorId { get; set; }

    public string RestrictionCode { get; set; }

    public string LifeFormCode { get; set; }

    public string CommonFertilizationCode { get; set; }

    public string IsNamePending { get; set; }

    public string SynonymCode { get; set; }

    public int? VerifierCooperatorId { get; set; }

    public DateTime? NameVerifiedDate { get; set; }

    public string Name { get; set; }

    public string NameAuthority { get; set; }

    public string Protologue { get; set; }

    public string ProtologueVirtualPath { get; set; }

    public string Note { get; set; }

    public string SiteNote { get; set; }

    public string AlternateName { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string HybridParentage { get; set; }

    public string IsWebVisible { get; set; }

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotationNewTaxonomySpecies { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<AccessionInvAnnotation> AccessionInvAnnotationOldTaxonomySpecies { get; set; } = new List<AccessionInvAnnotation>();

    public virtual ICollection<Accession> Accessions { get; set; } = new List<Accession>();

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual Cooperator Curator1Cooperator { get; set; }

    public virtual Cooperator Curator2Cooperator { get; set; }

    public virtual TaxonomySpecy CurrentTaxonomySpecies { get; set; }

    public virtual ICollection<InventoryViabilityRuleMap> InventoryViabilityRuleMaps { get; set; } = new List<InventoryViabilityRuleMap>();

    public virtual ICollection<TaxonomySpecy> InverseCurrentTaxonomySpecies { get; set; } = new List<TaxonomySpecy>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual Site Priority1Site { get; set; }

    public virtual Site Priority2Site { get; set; }

    public virtual TaxonomyGenu TaxonomyGenus { get; set; }

    public virtual Cooperator VerifierCooperator { get; set; }
}