// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class TaxonomyGenu
{
    public int TaxonomyGenusId { get; set; }

    public int? CurrentTaxonomyGenusId { get; set; }

    public int TaxonomyFamilyId { get; set; }

    public string QualifyingCode { get; set; }

    public string HybridCode { get; set; }

    public string GenusName { get; set; }

    public string GenusAuthority { get; set; }

    public string SubgenusName { get; set; }

    public string SectionName { get; set; }

    public string SubsectionName { get; set; }

    public string SeriesName { get; set; }

    public string SubseriesName { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string IsWebVisible { get; set; }

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual TaxonomyGenu CurrentTaxonomyGenus { get; set; }

    public virtual ICollection<TaxonomyGenu> InverseCurrentTaxonomyGenus { get; set; } = new List<TaxonomyGenu>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<TaxonomyFamily> TaxonomyFamilies { get; set; } = new List<TaxonomyFamily>();

    public virtual TaxonomyFamily TaxonomyFamily { get; set; }

    public virtual ICollection<TaxonomySpecy> TaxonomySpecies { get; set; } = new List<TaxonomySpecy>();
}