// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class TaxonomyFamily
{
    public int TaxonomyFamilyId { get; set; }

    public int? CurrentTaxonomyFamilyId { get; set; }

    public int? TypeTaxonomyGenusId { get; set; }

    public string SuprafamilyRankCode { get; set; }

    public string SuprafamilyRankName { get; set; }

    public string FamilyName { get; set; }

    public string FamilyAuthority { get; set; }

    public string AlternateName { get; set; }

    public string SubfamilyName { get; set; }

    public string TribeName { get; set; }

    public string SubtribeName { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string FamilyTypeCode { get; set; }

    public int? TaxonomyClassificationId { get; set; }

    public virtual ICollection<Citation> Citations { get; set; } = new List<Citation>();

    public virtual Cooperator CreatedByNavigation { get; set; }

    public virtual TaxonomyFamily CurrentTaxonomyFamily { get; set; }

    public virtual ICollection<TaxonomyFamily> InverseCurrentTaxonomyFamily { get; set; } = new List<TaxonomyFamily>();

    public virtual Cooperator ModifiedByNavigation { get; set; }

    public virtual Cooperator OwnedByNavigation { get; set; }

    public virtual ICollection<TaxonomyGenu> TaxonomyGenus { get; set; } = new List<TaxonomyGenu>();

    public virtual TaxonomyGenu TypeTaxonomyGenus { get; set; }
}