// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class VwGringlobalAccessionOverview
{
    public int AccessionId { get; set; }

    public string AccessionIdentifier { get; set; }

    public string PlantName { get; set; }

    public string Doi { get; set; }

    public int? TaxonomySpeciesId { get; set; }

    public string TaxonomySpeciesName { get; set; }

    public string GenebankName { get; set; }

    public string ImageUrl { get; set; }

    public string AvailabilityStatus { get; set; }

    public DateTime? ReceivedDate { get; set; }

    public int? ReceivedYear { get; set; }

    public string SourceType { get; set; }

    public string SourceDate { get; set; }

    public string SourceCollectionSite { get; set; }

    public string SourceCoordinates { get; set; }

    public string SourceElevation { get; set; }

    public string SourceHabitat { get; set; }

    public string ImprovementLevel { get; set; }

    public string Narrative { get; set; }
}