// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebCooperator
{
    public int WebCooperatorId { get; set; }

    public string LastName { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string Job { get; set; }

    public string Organization { get; set; }

    public string OrganizationCode { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string City { get; set; }

    public string PostalIndex { get; set; }

    public int? GeographyId { get; set; }

    public string PrimaryPhone { get; set; }

    public string SecondaryPhone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string IsActive { get; set; }

    public string CategoryCode { get; set; }

    public string OrganizationRegion { get; set; }

    public string Discipline { get; set; }

    public string Initials { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public string StatusCode { get; set; }

    public string VettedStatusCode { get; set; }

    public virtual ICollection<Cooperator> Cooperators { get; set; } = new List<Cooperator>();

    public virtual WebUser CreatedByNavigation { get; set; }

    public virtual Geography Geography { get; set; }

    public virtual WebUser ModifiedByNavigation { get; set; }

    public virtual WebUser OwnedByNavigation { get; set; }

    public virtual ICollection<WebOrderRequestAttach> WebOrderRequestAttaches { get; set; } = new List<WebOrderRequestAttach>();

    public virtual ICollection<WebOrderRequestItem> WebOrderRequestItems { get; set; } = new List<WebOrderRequestItem>();

    public virtual ICollection<WebOrderRequest> WebOrderRequests { get; set; } = new List<WebOrderRequest>();

    public virtual ICollection<WebUser> WebUsers { get; set; } = new List<WebUser>();
}