// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebOrderRequestAddress
{
    public int WebOrderRequestAddressId { get; set; }

    public int WebOrderRequestId { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string City { get; set; }

    public string PostalIndex { get; set; }

    public int? GeographyId { get; set; }

    public string Carrier { get; set; }

    public string CarrierAccount { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual WebUser CreatedByNavigation { get; set; }

    public virtual Geography Geography { get; set; }

    public virtual WebUser ModifiedByNavigation { get; set; }

    public virtual WebUser OwnedByNavigation { get; set; }

    public virtual WebOrderRequest WebOrderRequest { get; set; }
}