// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebOrderRequest
{
    public int WebOrderRequestId { get; set; }

    public int? WebCooperatorId { get; set; }

    public DateTime? OrderedDate { get; set; }

    public string IntendedUseCode { get; set; }

    public string IntendedUseNote { get; set; }

    public string StatusCode { get; set; }

    public string Note { get; set; }

    public string SpecialInstruction { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public bool? IsLocked { get; set; }

    public bool? EmailSent { get; set; }

    public virtual WebUser CreatedByNavigation { get; set; }

    public virtual ICollection<OrderRequest> OrderRequests { get; set; } = new List<OrderRequest>();

    public virtual WebUser OwnedByNavigation { get; set; }

    public virtual WebCooperator WebCooperator { get; set; }

    public virtual ICollection<WebOrderRequestAction> WebOrderRequestActions { get; set; } = new List<WebOrderRequestAction>();

    public virtual ICollection<WebOrderRequestAddress> WebOrderRequestAddresses { get; set; } = new List<WebOrderRequestAddress>();

    public virtual ICollection<WebOrderRequestAttach> WebOrderRequestAttaches { get; set; } = new List<WebOrderRequestAttach>();

    public virtual ICollection<WebOrderRequestItem> WebOrderRequestItems { get; set; } = new List<WebOrderRequestItem>();
}