// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebOrderRequestAction
{
    public int WebOrderRequestActionId { get; set; }

    public int WebOrderRequestId { get; set; }

    public string ActionCode { get; set; }

    public DateTime ActedDate { get; set; }

    public string ActionForId { get; set; }

    public string Note { get; set; }

    public int? WebCooperatorId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual WebOrderRequest WebOrderRequest { get; set; }
}