// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebOrderRequestAttach
{
    public int WebOrderRequestAttachId { get; set; }

    public int WebCooperatorId { get; set; }

    public int WebOrderRequestId { get; set; }

    public string VirtualPath { get; set; }

    public string ContentType { get; set; }

    public string Title { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual WebUser CreatedByNavigation { get; set; }

    public virtual WebUser ModifiedByNavigation { get; set; }

    public virtual WebUser OwnedByNavigation { get; set; }

    public virtual WebCooperator WebCooperator { get; set; }

    public virtual WebOrderRequest WebOrderRequest { get; set; }
}