// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebUserPreference
{
    public int WebUserPreferenceId { get; set; }

    public int WebUserId { get; set; }

    public string PreferenceName { get; set; }

    public string PreferenceValue { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual WebUser CreatedByNavigation { get; set; }

    public virtual WebUser ModifiedByNavigation { get; set; }

    public virtual WebUser OwnedByNavigation { get; set; }

    public virtual WebUser WebUser { get; set; }
}