// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRINGlobal.Data.Models;

public partial class WebUserCartItem
{
    public int WebUserCartItemId { get; set; }

    public int WebUserCartId { get; set; }

    public int AccessionId { get; set; }

    public int? Quantity { get; set; }

    public string FormTypeCode { get; set; }

    public string UsageCode { get; set; }

    public int? InventoryId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime OwnedDate { get; set; }

    public int OwnedBy { get; set; }

    public virtual Accession Accession { get; set; }

    public virtual WebUser CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual WebUser ModifiedByNavigation { get; set; }

    public virtual WebUser OwnedByNavigation { get; set; }

    public virtual WebUserCart WebUserCart { get; set; }
}