// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class citation
{
    public int citation_id { get; set; }

    public int? literature_id { get; set; }

    public string citation_title { get; set; }

    public string author_name { get; set; }

    public int? citation_year { get; set; }

    public string reference { get; set; }

    public string doi_reference { get; set; }

    public string url { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public int? accession_id { get; set; }

    public int? method_id { get; set; }

    public int? taxonomy_species_id { get; set; }

    public int? taxonomy_genus_id { get; set; }

    public int? taxonomy_family_id { get; set; }

    public int? accession_ipr_id { get; set; }

    public int? accession_pedigree_id { get; set; }

    public int? genetic_marker_id { get; set; }

    public string type_code { get; set; }

    public int? unique_key { get; set; }

    public string is_accepted_name { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual literature literature { get; set; }

    public virtual ICollection<taxonomy_common_name> taxonomy_common_name { get; set; } = new List<taxonomy_common_name>();

    public virtual ICollection<taxonomy_cwr> taxonomy_cwr { get; set; } = new List<taxonomy_cwr>();

    public virtual ICollection<taxonomy_cwr_map> taxonomy_cwr_map { get; set; } = new List<taxonomy_cwr_map>();

    public virtual ICollection<taxonomy_cwr_priority> taxonomy_cwr_priority { get; set; } = new List<taxonomy_cwr_priority>();

    public virtual ICollection<taxonomy_cwr_trait> taxonomy_cwr_trait { get; set; } = new List<taxonomy_cwr_trait>();

    public virtual taxonomy_family taxonomy_family { get; set; }

    public virtual taxonomy_genus taxonomy_genus { get; set; }

    public virtual ICollection<taxonomy_geography_map> taxonomy_geography_map { get; set; } = new List<taxonomy_geography_map>();

    public virtual taxonomy_species taxonomy_species { get; set; }

    public virtual ICollection<taxonomy_use> taxonomy_use { get; set; } = new List<taxonomy_use>();
}