// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class code_value_lang
{
    public int code_value_lang_id { get; set; }

    public int code_value_id { get; set; }

    public int sys_lang_id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual code_value code_value { get; set; }
}