// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class geography_region_map
{
    public int geography_region_map_id { get; set; }

    public int geography_id { get; set; }

    public int region_id { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual geography geography { get; set; }
}