// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class geography
{
    public int geography_id { get; set; }

    public int? current_geography_id { get; set; }

    public string country_code { get; set; }

    public string adm1 { get; set; }

    public string adm1_type_code { get; set; }

    public string adm1_abbrev { get; set; }

    public string adm2 { get; set; }

    public string adm2_type_code { get; set; }

    public string adm2_abbrev { get; set; }

    public string adm3 { get; set; }

    public string adm3_type_code { get; set; }

    public string adm3_abbrev { get; set; }

    public string adm4 { get; set; }

    public string adm4_type_code { get; set; }

    public string adm4_abbrev { get; set; }

    public DateTime? changed_date { get; set; }

    public string is_valid { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual ICollection<geography> Inversecurrent_geography { get; set; } = new List<geography>();

    public virtual geography current_geography { get; set; }

    public virtual ICollection<geography_region_map> geography_region_map { get; set; } = new List<geography_region_map>();

    public virtual ICollection<taxonomy_common_name> taxonomy_common_name { get; set; } = new List<taxonomy_common_name>();

    public virtual ICollection<taxonomy_geography_map> taxonomy_geography_map { get; set; } = new List<taxonomy_geography_map>();

    public virtual ICollection<taxonomy_regulation> taxonomy_regulation { get; set; } = new List<taxonomy_regulation>();
}