// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_species_upov
{
    public int taxonomy_species_upov_id { get; set; }

    public int? upov_code_id { get; set; }

    public string upov_code { get; set; }

    public string principal_botanical_name { get; set; }

    public string other_botanical_name { get; set; }

    public string common_name_text { get; set; }

    public string note { get; set; }

    public int? taxonomy_species_id { get; set; }

    public virtual taxonomy_species taxonomy_species { get; set; }
}