// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_common_name_language
{
    public int taxonomy_common_name_language_id { get; set; }

    public string language_name { get; set; }

    public string language_simplified_name { get; set; }

    public string language_transcription { get; set; }

    public string country_code { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public string note { get; set; }

    public virtual ICollection<taxonomy_common_name> taxonomy_common_name { get; set; } = new List<taxonomy_common_name>();
}