// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_species_synonym_map
{
    public int taxonomy_species_synonym_map_id { get; set; }

    public int taxona_taxonomy_species_id { get; set; }

    public string synonym_code { get; set; }

    public int taxonb_taxonomy_species_id { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual taxonomy_species taxona_taxonomy_species { get; set; }

    public virtual taxonomy_species taxonb_taxonomy_species { get; set; }
}