// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_subfamily
{
    public int taxonomy_subfamily_id { get; set; }

    public int? accepted_taxonomy_family_map_id { get; set; }

    public int? type_taxonomy_genus_id { get; set; }

    public int? taxonomy_family2_id { get; set; }

    public string subfamily_name { get; set; }

    public string subfamily_authority { get; set; }

    public string note { get; set; }

    public int? created_by { get; set; }

    public DateTime? created_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? owned_by { get; set; }

    public DateTime? owned_date { get; set; }
}