// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_attach
{
    public int taxonomy_attach_id { get; set; }

    public int? taxonomy_family_id { get; set; }

    public int? taxonomy_genus_id { get; set; }

    public int? taxonomy_species_id { get; set; }

    public string virtual_path { get; set; }

    public string thumbnail_virtual_path { get; set; }

    public int? sort_order { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public string content_type { get; set; }

    public string category_code { get; set; }

    public string is_web_visible { get; set; }

    public string copyright_information { get; set; }

    public int? attach_cooperator_id { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual taxonomy_family taxonomy_family { get; set; }

    public virtual taxonomy_genus taxonomy_genus { get; set; }

    public virtual taxonomy_species taxonomy_species { get; set; }
}