// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_alt_family_map
{
    public int taxonomy_alt_family_map_id { get; set; }

    public int taxonomy_genus_id { get; set; }

    public int taxonomy_family_id { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual taxonomy_family taxonomy_family { get; set; }

    public virtual taxonomy_genus taxonomy_genus { get; set; }
}