// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_cwr
{
    public int taxonomy_cwr_id { get; set; }

    public int taxonomy_species_id { get; set; }

    public string crop_name { get; set; }

    public string display_name { get; set; }

    public string crop_common_name { get; set; }

    public string is_crop { get; set; }

    public string genepool_code { get; set; }

    public string is_graftstock_genepool { get; set; }

    public string trait_class_code { get; set; }

    public string is_potential { get; set; }

    public string breeding_type_code { get; set; }

    public string breeding_usage { get; set; }

    public string ontology_trait_identifier { get; set; }

    public int? citation_id { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual citation citation { get; set; }

    public virtual taxonomy_species taxonomy_species { get; set; }
}