// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_family
{
    public int taxonomy_family_id { get; set; }

    public int? current_taxonomy_family_id { get; set; }

    public int? type_taxonomy_genus_id { get; set; }

    public string suprafamily_rank_code { get; set; }

    public string suprafamily_rank_name { get; set; }

    public string family_name { get; set; }

    public string family_authority { get; set; }

    public string alternate_name { get; set; }

    public string subfamily_name { get; set; }

    public string tribe_name { get; set; }

    public string subtribe_name { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public string family_type_code { get; set; }

    public int? taxonomy_classification_id { get; set; }

    public virtual ICollection<taxonomy_family> Inversecurrent_taxonomy_family { get; set; } = new List<taxonomy_family>();

    public virtual ICollection<citation> citation { get; set; } = new List<citation>();

    public virtual taxonomy_family current_taxonomy_family { get; set; }

    public virtual ICollection<taxonomy_alt_family_map> taxonomy_alt_family_map { get; set; } = new List<taxonomy_alt_family_map>();

    public virtual ICollection<taxonomy_attach> taxonomy_attach { get; set; } = new List<taxonomy_attach>();

    public virtual ICollection<taxonomy_genus> taxonomy_genus { get; set; } = new List<taxonomy_genus>();

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seedalternate_family_id_1Navigation { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seedalternate_family_id_2Navigation { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seedalternate_family_id_3Navigation { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seedprimary_family { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_regulation_map> taxonomy_regulation_map { get; set; } = new List<taxonomy_regulation_map>();

    public virtual taxonomy_genus type_taxonomy_genus { get; set; }
}