// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_folder
{
    public int taxonomy_folder_id { get; set; }

    public string title { get; set; }

    public string category { get; set; }

    public string description { get; set; }

    public string note { get; set; }

    public bool? is_shared { get; set; }

    public string data_source_name { get; set; }

    public string data_source_title { get; set; }

    public int? created_by { get; set; }

    public DateTime? created_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime? modified_date { get; set; }

    public bool? is_favorite { get; set; }

    public virtual ICollection<taxonomy_folder_item_map> taxonomy_folder_item_map { get; set; } = new List<taxonomy_folder_item_map>();
}