// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_folder_item_map
{
    public int taxonomy_folder_item_id { get; set; }

    public int taxonomy_folder_id { get; set; }

    public int item_id { get; set; }

    public int? created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string data_source { get; set; }

    public virtual taxonomy_folder taxonomy_folder { get; set; }
}