// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_ref_upov_crop
{
    public int taxonomy_ref_upov_crop_id { get; set; }

    public string upov_code { get; set; }

    public string url { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public int? upov_crop_id { get; set; }

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seed { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_upov_crop_map> taxonomy_upov_crop_map { get; set; } = new List<taxonomy_upov_crop_map>();
}