// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_author
{
    public int taxonomy_author_id { get; set; }

    public string short_name { get; set; }

    public string full_name { get; set; }

    public string short_name_expanded_diacritic { get; set; }

    public string full_name_expanded_diacritic { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }
}