// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_genus
{
    public int taxonomy_genus_id { get; set; }

    public int? current_taxonomy_genus_id { get; set; }

    public int taxonomy_family_id { get; set; }

    public string qualifying_code { get; set; }

    public string hybrid_code { get; set; }

    public string genus_name { get; set; }

    public string genus_authority { get; set; }

    public string subgenus_name { get; set; }

    public string section_name { get; set; }

    public string subsection_name { get; set; }

    public string series_name { get; set; }

    public string subseries_name { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public string is_web_visible { get; set; }

    public virtual ICollection<taxonomy_genus> Inversecurrent_taxonomy_genus { get; set; } = new List<taxonomy_genus>();

    public virtual ICollection<citation> citation { get; set; } = new List<citation>();

    public virtual taxonomy_genus current_taxonomy_genus { get; set; }

    public virtual ICollection<taxonomy_alt_family_map> taxonomy_alt_family_map { get; set; } = new List<taxonomy_alt_family_map>();

    public virtual ICollection<taxonomy_attach> taxonomy_attach { get; set; } = new List<taxonomy_attach>();

    public virtual ICollection<taxonomy_common_name> taxonomy_common_name { get; set; } = new List<taxonomy_common_name>();

    public virtual ICollection<taxonomy_family> taxonomy_family { get; set; } = new List<taxonomy_family>();

    public virtual taxonomy_family taxonomy_familyNavigation { get; set; }

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seed { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_regulation_map> taxonomy_regulation_map { get; set; } = new List<taxonomy_regulation_map>();

    public virtual ICollection<taxonomy_species> taxonomy_species { get; set; } = new List<taxonomy_species>();
}