// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_regulation
{
    public int taxonomy_regulation_id { get; set; }

    public int geography_id { get; set; }

    public string regulation_type_code { get; set; }

    public string regulation_level_code { get; set; }

    public string description { get; set; }

    public string url_1 { get; set; }

    public string url_2 { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual geography geography { get; set; }

    public virtual ICollection<taxonomy_regulation_map> taxonomy_regulation_map { get; set; } = new List<taxonomy_regulation_map>();
}