// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_ista_seed
{
    public int taxonomy_ista_seed_id { get; set; }

    public int? taxonomy_species_id { get; set; }

    public string name_status { get; set; }

    public int? accepted_taxonomy_species_id { get; set; }

    public int? primary_family_id { get; set; }

    public int? alternate_family_id_1 { get; set; }

    public int? alternate_family_id_2 { get; set; }

    public int? alternate_family_id_3 { get; set; }

    public string url { get; set; }

    public string note { get; set; }

    public string comment { get; set; }

    public int? taxonomy_upov_crop_map_id { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public int? family_id_2 { get; set; }

    public int? family_id_3 { get; set; }

    public int? taxonomy_genus_id { get; set; }

    public int? taxonomy_upov_crop_id { get; set; }

    public string TEMP_UPOV { get; set; }

    public string primary_family_name { get; set; }

    public string family_name_2 { get; set; }

    public virtual taxonomy_family alternate_family_id_1Navigation { get; set; }

    public virtual taxonomy_family alternate_family_id_2Navigation { get; set; }

    public virtual taxonomy_family alternate_family_id_3Navigation { get; set; }

    public virtual taxonomy_family primary_family { get; set; }

    public virtual taxonomy_genus taxonomy_genus { get; set; }

    public virtual taxonomy_species taxonomy_species { get; set; }

    public virtual taxonomy_ref_upov_crop taxonomy_upov_crop { get; set; }
}