// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_geography_map
{
    public int taxonomy_geography_map_id { get; set; }

    public int taxonomy_species_id { get; set; }

    public int? geography_id { get; set; }

    public string geography_status_code { get; set; }

    public int? citation_id { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual citation citation { get; set; }

    public virtual geography geography { get; set; }

    public virtual taxonomy_species taxonomy_species { get; set; }
}