// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_cwr_priority
{
    public int taxonomy_cwr_priority_id { get; set; }

    public int taxonomy_species_id { get; set; }

    public int priority_year { get; set; }

    public string status_code { get; set; }

    public string in_situ_code { get; set; }

    public string ex_situ_code { get; set; }

    public int? citation_id { get; set; }

    public string note { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public virtual citation citation { get; set; }

    public virtual taxonomy_species taxonomy_species { get; set; }
}