// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace USDA.ARS.GRIN.GRINGlobal.API.Data.Models;

public partial class taxonomy_species
{
    public int taxonomy_species_id { get; set; }

    public int? current_taxonomy_species_id { get; set; }

    public int? nomen_number { get; set; }

    public string is_specific_hybrid { get; set; }

    public string species_name { get; set; }

    public string species_authority { get; set; }

    public string is_subspecific_hybrid { get; set; }

    public string subspecies_name { get; set; }

    public string subspecies_authority { get; set; }

    public string is_varietal_hybrid { get; set; }

    public string variety_name { get; set; }

    public string variety_authority { get; set; }

    public string is_subvarietal_hybrid { get; set; }

    public string subvariety_name { get; set; }

    public string subvariety_authority { get; set; }

    public string is_forma_hybrid { get; set; }

    public string forma_rank_type { get; set; }

    public string forma_name { get; set; }

    public string forma_authority { get; set; }

    public int taxonomy_genus_id { get; set; }

    public int? priority1_site_id { get; set; }

    public int? priority2_site_id { get; set; }

    public int? curator1_cooperator_id { get; set; }

    public int? curator2_cooperator_id { get; set; }

    public string restriction_code { get; set; }

    public string life_form_code { get; set; }

    public string common_fertilization_code { get; set; }

    public string is_name_pending { get; set; }

    public string synonym_code { get; set; }

    public int? verifier_cooperator_id { get; set; }

    public DateTime? name_verified_date { get; set; }

    public string name { get; set; }

    public string name_authority { get; set; }

    public string protologue { get; set; }

    public string protologue_virtual_path { get; set; }

    public string note { get; set; }

    public string site_note { get; set; }

    public string alternate_name { get; set; }

    public DateTime created_date { get; set; }

    public int created_by { get; set; }

    public DateTime? modified_date { get; set; }

    public int? modified_by { get; set; }

    public DateTime owned_date { get; set; }

    public int owned_by { get; set; }

    public string hybrid_parentage { get; set; }

    public string is_web_visible { get; set; }

    public virtual ICollection<taxonomy_species> Inversecurrent_taxonomy_species { get; set; } = new List<taxonomy_species>();

    public virtual ICollection<citation> citation { get; set; } = new List<citation>();

    public virtual taxonomy_species current_taxonomy_species { get; set; }

    public virtual ICollection<taxonomy_attach> taxonomy_attach { get; set; } = new List<taxonomy_attach>();

    public virtual ICollection<taxonomy_common_name> taxonomy_common_name { get; set; } = new List<taxonomy_common_name>();

    public virtual ICollection<taxonomy_crop_map> taxonomy_crop_map { get; set; } = new List<taxonomy_crop_map>();

    public virtual ICollection<taxonomy_cwr> taxonomy_cwr { get; set; } = new List<taxonomy_cwr>();

    public virtual ICollection<taxonomy_cwr_map> taxonomy_cwr_map { get; set; } = new List<taxonomy_cwr_map>();

    public virtual ICollection<taxonomy_cwr_priority> taxonomy_cwr_priority { get; set; } = new List<taxonomy_cwr_priority>();

    public virtual taxonomy_genus taxonomy_genus { get; set; }

    public virtual ICollection<taxonomy_geography_map> taxonomy_geography_map { get; set; } = new List<taxonomy_geography_map>();

    public virtual ICollection<taxonomy_ista_seed> taxonomy_ista_seed { get; set; } = new List<taxonomy_ista_seed>();

    public virtual ICollection<taxonomy_regulation_map> taxonomy_regulation_map { get; set; } = new List<taxonomy_regulation_map>();

    public virtual ICollection<taxonomy_species_synonym_map> taxonomy_species_synonym_maptaxona_taxonomy_species { get; set; } = new List<taxonomy_species_synonym_map>();

    public virtual ICollection<taxonomy_species_synonym_map> taxonomy_species_synonym_maptaxonb_taxonomy_species { get; set; } = new List<taxonomy_species_synonym_map>();

    public virtual ICollection<taxonomy_species_upov> taxonomy_species_upov { get; set; } = new List<taxonomy_species_upov>();

    public virtual ICollection<taxonomy_upov_crop_map> taxonomy_upov_crop_map { get; set; } = new List<taxonomy_upov_crop_map>();

    public virtual ICollection<taxonomy_use> taxonomy_use { get; set; } = new List<taxonomy_use>();
}